---
title: "assessing performance"
author: "Maria Burzillo"
date: "2/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r import data, include = FALSE}
tracts_selected_predictions <- read.csv("selected_tract_predictions.csv") %>%
  mutate(treatment = as.factor(treatment))

# remove any observations unable to get prediction for 
tracts_selected_predictions <- tracts_selected_predictions %>%
  filter(!(is.na(predicted_pct_d)))
```

```{r}
tracts_selected_predictions %>%
  ggplot(aes(x = predicted_pct_d, color = treatment)) +
  geom_density() +
  ggtitle("Predicted Grade D by Tract: Treatment and Control Groups")
```

```{r}
# average population

tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(tot_persons_printed))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(tot_persons_printed))

# pct_AA

tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_black_printed))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_black_printed))

# pct_foreign_born

tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_foreign_born))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_foreign_born))


# pct_unemployed_males

tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_unemployed_males))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_unemployed_males))

# pct_owner_occupied

tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_owner_occupied, na.rm = T))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_owner_occupied, na.rm = T))

# pct_contract_rent_lt_50

tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_contract_rent_lt_50, na.rm = T))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_contract_rent_lt_50, na.rm = T))

# pct_vacant_all"

tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_vacant_all, na.rm = T))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_vacant_all, na.rm = T))


# pct_one_point_0_one_people_per_room_or_more

tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_one_point_0_one_people_per_r, na.rm = T))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_one_point_0_one_people_per_r, na.rm = T))

#  "pct_single_unit"   

tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_single_unit, na.rm = T))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_single_unit, na.rm = T))

# pct_housing_deteriorated_dilap

tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_housing_deteriorated_dilap, na.rm = T))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_housing_deteriorated_dilap, na.rm = T))

# "weighted_cash_contract_rent"         

tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(weighted_cash_contract_rent, na.rm = T))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(weighted_cash_contract_rent, na.rm = T))

tracts_selected_predictions  %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pop_density, na.rm = T))

tracts_selected_predictions %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pop_density, na.rm = T))

```

```{r}

tracts_predicted_red <- tracts_selected_predictions %>%
  filter(predicted_pct_d >= 50)
```

```{r}
# average population

tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(tot_persons_printed))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(tot_persons_printed))

# pct_AA

tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_black_printed))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_black_printed))

# pct_foreign_born

tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_foreign_born))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_foreign_born))


# pct_unemployed_males

tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_unemployed_males))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_unemployed_males))

# pct_owner_occupied

tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_owner_occupied, na.rm = T))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_owner_occupied, na.rm = T))

# pct_contract_rent_lt_50

tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_contract_rent_lt_50, na.rm = T))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_contract_rent_lt_50, na.rm = T))

# pct_vacant_all"

tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_vacant_all, na.rm = T))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_vacant_all, na.rm = T))


# pct_one_point_0_one_people_per_room_or_more

tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_one_point_0_one_people_per_r, na.rm = T))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_one_point_0_one_people_per_r, na.rm = T))

#  "pct_single_unit"   

tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_single_unit, na.rm = T))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_single_unit, na.rm = T))

# pct_housing_deteriorated_dilap

tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_housing_deteriorated_dilap, na.rm = T))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_housing_deteriorated_dilap, na.rm = T))

# "weighted_cash_contract_rent"         

tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(weighted_cash_contract_rent, na.rm = T))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(weighted_cash_contract_rent, na.rm = T))


tracts_predicted_red %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pop_density, na.rm = T))

tracts_predicted_red %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pop_density, na.rm = T))
```

```{r}

tracts_selected_predictions %>%
  filter(treatment == 1)
```


```{r}
colnames(tracts_selected_predictions)
```

```{r}

# idea is to figure out, out of all the tracts, which were used in prediction and final model

potential_treatment_data_for_analysis_gis <- data_for_analysis %>%
  filter(citypop_total > 40000, citypop_total <= 60000,
         area_accounted_for >= .5) %>%
  select(GISJOIN)
  
potential_treatment_data_for_analysis <- data_for_analysis %>%
  filter(citypop_total > 40000, citypop_total <= 60000,
         area_accounted_for >= .5)

data_for_analysis %>%
  mutate(count = 1) %>%
  group_by(GISJOIN) %>%
  mutate(sum_count = sum(count)) %>%
  filter(sum_count != 1)

treatment_tracts_selected_predictions <- tracts_selected_predictions %>%
  filter(treatment == 1)

treatment_tracts_selected_predictions_gis <- tracts_selected_predictions %>%
  filter(treatment == 1) %>%
  select(GISJOIN = gisjoin)

# returns all rows in x with a match in y
semi_join(potential_treatment_data_for_analysis_gis, treatment_tracts_selected_predictions_gis)

# all tracts selected that are not in the original group
gis_extra <- anti_join(treatment_tracts_selected_predictions_gis,potential_treatment_data_for_analysis_gis)$GISJOIN

# all tracts in original that are not selected
anti_join(potential_treatment_data_for_analysis_gis, treatment_tracts_selected_predictions_gis)

333


```

```{r summary statistics of tracts by model selection}
# treatment_tracts_selected_predictions 

# potential_treatment_data_for_analysis


mean(potential_treatment_data_for_analysis$tot_persons_printed)
mean(potential_treatment_data_for_analysis$pct_black_printed)
mean(potential_treatment_data_for_analysis$pct_foreign_born)
mean(potential_treatment_data_for_analysis$pct_unemployed_males)
mean(potential_treatment_data_for_analysis$pct_owner_occupied)

mean(potential_treatment_data_for_analysis$pct_contract_rent_lt_50)
mean(potential_treatment_data_for_analysis$pct_vacant_all)
mean(potential_treatment_data_for_analysis$pct_one_point_0_one_people_per_room_or_more)
mean(potential_treatment_data_for_analysis$pct_housing_deteriorated_dilap)
mean(potential_treatment_data_for_analysis$weighted_cash_contract_rent)
mean(potential_treatment_data_for_analysis$pop_density)


extra_selected <- tracts_selected_predictions %>%
  filter(gisjoin %in% gis_extra)

mean(extra_selected$tot_persons_printed)
mean(extra_selected$pct_black_printed)
mean(extra_selected$pct_foreign_born)
mean(extra_selected$pct_unemployed_males)
mean(extra_selected$pct_owner_occupied)
mean(extra_selected$pct_single_unit)

mean(extra_selected$pct_contract_rent_lt_50)
mean(extra_selected$pct_vacant_all)
mean(extra_selected$pct_one_point_0_one_people_per_r)
mean(extra_selected$pct_housing_deteriorated_dilap)
mean(extra_selected$weighted_cash_contract_rent)
mean(extra_selected$pop_density)
```


```{r}
colnames(extra_selected)
```

