---
title: "Calculating 1930 City Populations"
author: "Maria Burzillo"
date: "12/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(readxl)
library(sjmisc)
library(sf)
```

```{r import ipums data containing city and citypop for 1930 census, include = FALSE}

city_codebook_1930_full_sample <- read_excel("1930 City Population Data/city_codebook_1930_full_sample.xlsx") %>%
  select(-city_name)

# import list of all cities that have HOLC maps

all_cities_in_richmond <- read_excel("all_cities_in_richmond.xlsx")

# import data from 1930 full sample that I collapsed on Suz'z computer: hopefully this will be the final dataset...
ipums_full_sample_collapsed_1930 <- read_csv("1930 City Population Data/1930_data_ipums_full_sample_collapsed.csv")

```


```{r reshaping data to get 1 obs per city}

# Definition of CITY: CITY identifies the city of residence for households located in identifiable cities. The Comparability section provides a discussion of factors affecting which cities are identified and how well they are represented in each sample. The cities identified by CITY are generally consistent with U.S. Census "place" definitions. For an explanation and history of the concept, see Chapter 9 in the Census Bureau's Geographic Areas Reference Manual.

# Definition of CITYPOP: CITYPOP reports the population, in hundreds, for all identifiable cities. For Decennial Census samples, CITYPOP reports the counts collected in that Decennial Census. For the 2005 ACS sample, CITYPOP reports populations estimates derived for the 2005 ACS. For ACS samples from 2006-2011, CITYPOP reports population estimates derived from the 2006 ACS. For the 2012-onward ACS, CITYPOP reports population estimates derived from the ACS of that year. CITYPOP is a 5-digit numeric variable that reports the population, in hundreds, for all identifiable cities. For instance, a city having a population of 1,234,500 will have a CITYPOP value of 12345. For all samples prior to 1940 and the 1940 100% dataset, CITYPOP reports the population for all incorporated municipalities


# ipums_collapsed %>% filter(CITY == 1670)
# Q: what does it mean when citypop is given 0 for a city when perwt is non-zero?: seems like 0 corresponds to a city not identified or unincorporated place response. 
ipums_full_sample_collapsed_1930 <- ipums_full_sample_collapsed_1930  %>%
  rename(citypop_hundreds = citypop) %>%
  mutate(citypop_total = 100 * citypop_hundreds) 

# there are 8 cities which appear to have populations greater than 30,000 and yet do not have a citypop encoded. Should check later if any cities graded by HOLC are missing and see if they are one of these
ipums_full_sample_collapsed_1930 %>%
  filter(citypop_hundreds == 0, perwt > 30000)

# Brooklyn is not in sample (expected because codebook says it is only in sample before 1900)
ipums_full_sample_collapsed_1930 %>%
  filter(city == "4611")


```


```{r edit city codebook to merge with names, include = FALSE}

############### WITH FULL SAMPLE ##############

# these are the entries that do not have states/are irregular. 2 cities dropped below. Rest of cities just kept with NA for state
city_codebook_1930_full_sample_edited <- city_codebook_1930_full_sample %>%
  separate(city, c("city", "cityname"), sep = 4)  %>%
  # drop 1860 because no info in codebook and 0 because city could not be identified.
  filter(city != "0000") %>%
  filter(!(str_detect(cityname, ",")))
  


# Cleaning the full sample codebook (unclear if this is actually different from the 1%/5% one but want to be safe)  
city_codebook_1930_full_sample_edited <- city_codebook_1930_full_sample %>%
  # drop cities without city codes
  filter(city != "Georgetown, DC (See Washington, DC)", city != "Brooklyn, NY (See NYC)", 
         city != "Northern Liberties, PA (See Philadelphia)",
         city != "Southwark, PA (See Philadelphia)",
         city != "Spring Garden, PA (See Philadelphia)") %>%
  # separate city code from city name
  separate(city, c("city", "cityname"), sep = 4)  %>%
  # drop 1860 because no info in codebook and 0 because city could not be identified. Exclude city 1860 because city name is blank in codebook. Exclude Brooklyn (4611) because only in censuses before 1900 and so not relevant
  filter(city != "0000", city != "1860", city != "4611") %>%
  #separate city name from state name
  separate(cityname, c("cityname", "state"), ",") %>%
  # drop space before the state name
  separate(state, c("empty", "state"), sep = 1) %>%
  # drop anything after the state name
  separate(state, c("state", "drop"), sep = 2) %>%
  # drop excess rows/rows that have been separated
  select(-empty, -drop) %>%
  rename(CITY_old = city) %>%
  # remove leading zeros from city identifier name
  mutate(city = as.numeric(str_remove(CITY_old, "^0+")),
         cityname = trimws(cityname))

city_codebook_1930_full_sample_edited$cityname[city_codebook_1930_full_sample_edited$city == 2683] <- "Hanover township, Luzerne county"
city_codebook_1930_full_sample_edited$state[city_codebook_1930_full_sample_edited$city == 2683] <- "PA"

write.csv(city_codebook_1930_full_sample_edited , "city_codebook_1930_full_sample_edited")  
```



```{r join ipums data with city codebook, include = FALSE}

####### WITH FULL SAMPLE ###########

# joining codebook with full sample gives 984 cities/same number as in full collapsed sample -> looks good
ipums_1930_cities_by_pop_full_sample <- left_join(ipums_full_sample_collapsed_1930, city_codebook_1930_full_sample_edited)

# these cities correspond exactly to the cities between 30k and 40k that I had originally identified 
ipums_1930_cities_by_pop_full_sample %>%
  filter(citypop_total > 40000, citypop_total < 50000)

ipums_1930_cities_by_pop_full_sample %>%
  filter(citypop_total > 60000)


```


```{r join all cities in richmond to ipums data}

# join all cities with HOLC maps in Richmond with city population data from 1930. This will allow us to filter cities by various population cutoffs. First task will be to make sure that the cities that did not automcatically join correctly are corrected.

# create a new names variable to reflect any changes made to how they were originally in Richmond
all_cities_in_richmond$city_name_edited <- all_cities_in_richmond$City

# corrections based on spelling
all_cities_in_richmond$city_name_edited[all_cities_in_richmond$City == "East Saint Louis"] <- "East St. Louis"
all_cities_in_richmond$city_name_edited[all_cities_in_richmond$City == "Schenectady"] <- "Schenectedy"
# exclude the following for now
# all_cities_in_richmond$city_name_edited[all_cities_in_richmond$City == "Lake Co. Gary"] <- "Gary"
# all_cities_in_richmond$city_name_edited[all_cities_in_richmond$City == "Greater Kansas City"] <- "Kansas City"



# joining correctly length-wise
city_pop_name_1930_in_richmond <- left_join(all_cities_in_richmond, ipums_1930_cities_by_pop_full_sample, by = c("city_name_edited" = "cityname", "state_ab" = "state")) %>%
  rename(city_code = city)


# with the initial join, it seems that only 20 cities did not join correctly -> likey a city designaiton or spelling mismatch error

city_pop_name_1930_in_richmond %>%
  filter(is.na(city_code))



# dropping some cities for now based on inability to match

cities_to_exclude = c("Stamford, Darien, and New Canaan", "Holyoke Chicopee", "Bergen Co.", "Essex Co.", 
                      "Hudson Co.", "Union Co.", "Binghamton-Johnson City", "Lower Westchester Co.",
                      "Pawtucket and Central Falls", "Milwaukee Co.", "Lake Co. Gary", "Greater Kansas City" )

city_pop_name_1930_in_richmond <- city_pop_name_1930_in_richmond %>%
  filter(!(City %in% cities_to_exclude))

# need to drop Lexington differently because also Lexington Kentucky here

city_pop_name_1930_in_richmond <- city_pop_name_1930_in_richmond[!(city_pop_name_1930_in_richmond$City == "Lexington" & city_pop_name_1930_in_richmond$state_ab == "MA"),]


city_pop_name_1930_in_richmond %>%
  filter(is.na(city_code))


######################## Notes on mismatches ##################################3
# East Saint Louis v. East St. Louis -> spelling uniformized 
# Stamford, Darien, and New Canaan (have data for Stamford but not Darien or New Canaan. Stamford has citypop of 46,300 so could be in treatment group, especially if these 3 cities make up 1 urban area. It is included in Aaronson) -> exclude for now
# Lake Co. Gary Indiana seems a definitely match to Gary Indiana in IPUMS. Lake County is the county name that Gary is in. Not sure why the put that in the name but changing to just Gary
# Massachusetts	Holyoke Chicopee (Holyoke and Chicopee available separately. Pop of Chicopee IS 43,900. Population of Holyoke is 56500. Chicopee and Holyoke are included in Aaronson). Based on the maps, they seem to make up 1 larger urban area. Exclude for now but could be added back in later as part of the larger cities
# Lexington, MA is not in the city codebook. May not have been incorporated at the time according to census sheet, only population of 9k at the time. Exclude for now. Could be included later since part of the area mapped for Boston but...
# Greater Kansas city includes city over the Kansas border. Should be fine to include. If anything, Kansas City match would be an underestimate, which would not be a problem because the population is 399,700 and thus already way above the threshold. Kansas City Kansas has population 121,800 so both well over threshold

# Issue of NJ: most maps around NYC seem to be made corresponding to counties rather than cities. All seem to be part of the larger NYC area
  # Bergen Co. seems to be a part of the larger NYC area. No direct match in census, but there is a North Bergen. However this is part of      # Hudson county, not Bergen county. Doesn't seem to have any cities large enough to be inclued in analysis
  # Essex Co. same situation. No direct match, but Essex county contains Newark, which had a population of 442300 ->> should this be 
  # included?
  # Hudson Co. same deal. No direct match, but contains Jersey City (pop 316700) and North Bergen (North Bergen has a        
  # population only of 40,715. If anything, this should be included in the treatment group, however, citypop = 0, meaning the place was not 
  # incorporated.) . --> should this be included?
  # Union Co. same deal. Contains cities such as Union (too small/citypop 0) and Elizabeth (pop 114,500) -> should we include?

# Binghamton-Johnson City. Both Binghamton (pop 76600) and Johnson (pop 13500) can be found separately in the Census --> should we include?

# Cities around NYC in NY. 
# Bronx has no match
# Brooklyn is entered with no city code and a note to see NYC. Seems to be counted within NYC (pop 6,930,400)
# Lower Westchester Co. seems to be the same situation as with the NJ counties near NYC. No direct match. Contains Yonkers (pop 134,600), New Rochelle (pop 54,000), White Plains (pop 35,800)
# Manhattan is not in the Census, this seems to be included in NYC


# According to census records (https://www2.census.gov/library/publications/decennial/1930/population-volume-1/03815512v1ch07.pdf), NYC contains the 5 boroughs of Bronx, Brooklyn, Manhattan, Queens, and Richmond (Staten Island). All had 1930 pops well over 60k. Should all be included. Writing in these population numbers from the census doc linked here.

city_pop_name_1930_in_richmond$citypop_total[city_pop_name_1930_in_richmond$City == "Bronx"] <- 1265258
city_pop_name_1930_in_richmond$citypop_total[city_pop_name_1930_in_richmond$City == "Brooklyn"] <- 2560401
city_pop_name_1930_in_richmond$citypop_total[city_pop_name_1930_in_richmond$City == "Manhattan"] <- 1867312
city_pop_name_1930_in_richmond$citypop_total[city_pop_name_1930_in_richmond$City == "Queens"] <- 1079129
city_pop_name_1930_in_richmond$citypop_total[city_pop_name_1930_in_richmond$City == "Staten Island"] <- 158346


# Pawtucket and Central Falls is in census separately as Pawtucket (pop 77,100) and Central Falls (pop 25800) -> exclude for now but clearly 2 cities directly next to eachother with a combiend pop well over 60k

# Milwaukee Co. is not directly in the census but Milwaukee city is with population 578,200. The county seems to be a slightly bigger area than the city, but not by much... excluded for now but seems like this should really be included. If anything, population would be underestimate.

city_pop_name_1930_in_richmond %>%
  filter(is.na(citypop_total))

ipums_1930_cities_by_pop_full_sample %>% filter(cityname == "Fort Worth")


```


```{r summary statistics, include = FALSE}

###################### cities in Richmond/HOLC cities
# 189 cities overall
city_pop_name_1930_in_richmond

# cities 30-40k: 3 

city_pop_name_1930_in_richmond %>%
  filter(citypop_total > 30000 & citypop_total < 40000)

# cities 40-50k: 30

city_pop_name_1930_in_richmond %>%
  filter(citypop_total > 40000 & citypop_total < 50000)

# cities 20-40k: 5

city_pop_name_1930_in_richmond %>%
  filter(citypop_total > 20000 & citypop_total < 40000)

# cities 40-60k: 56

city_pop_name_1930_in_richmond %>%
  filter(citypop_total > 40000 & citypop_total < 60000)

# cities 60k+: 117
city_pop_name_1930_in_richmond %>%
  filter(citypop_total > 60000)


########################## full city sample
# ALL: 984
ipums_1930_cities_by_pop_full_sample 

# cities 30-40k: 217
ipums_1930_cities_by_pop_full_sample %>%
  filter(citypop_total > 20000 & citypop_total < 40000)

# cities 30-40k: 71
ipums_1930_cities_by_pop_full_sample %>%
  filter(citypop_total > 30000 & citypop_total < 40000)


# # cities 40-50k: 45
ipums_1930_cities_by_pop_full_sample %>%
  filter(citypop_total > 40000 & citypop_total < 50000)

# # cities 40-60k: 83
ipums_1930_cities_by_pop_full_sample %>%
  filter(citypop_total > 40000 & citypop_total < 60000)

# # cities 60k + : 153
ipums_1930_cities_by_pop_full_sample %>%
  filter(citypop_total > 60000)

# less than 20k
ipums_1930_cities_by_pop_full_sample %>%
  filter(citypop_total < 20000)
```


# subset after the join...

```{r create subsets based on city size, include = FALSE}

cities_60k_plus_full_sample <- ipums_1930_cities_by_pop_full_sample %>%
  filter(citypop_total > 60000)


```

