---
title: "Demographic and Tract Merge"
author: "Maria Burzillo"
date: "11/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(rstanarm)
library(tidyverse)
```

```{r import data, include = FALSE}

# read in the IPUMS file with census tract level data on race and other deomgraphic characteristics

# initial data: sub-data
# nhgis0019_ds92_1960_tract <- read_csv("Demographic Data/nhgis0019_csv/nhgis0019_ds92_1960_tract.csv")

# load demographic data that contains all potential variables
nhgis0023_ds92_1960_tract <- read_csv("Demographic Data/1960 All Vars/nhgis0023_csv/nhgis0023_ds92_1960_tract.csv")


# rename file

race_1960_demo <- nhgis0023_ds92_1960_tract

all_richmond_with_pop %>%
  filter(city == "Atlantic City")

race_1960_demo %>%
  filter(GISJOIN == "G3400070CJ0045")


nhgis0023_ds92_1960_tract %>%
  mutate(count = 1) %>%
  group_by(GISJOIN) %>%
  mutate(sum_count = sum(count)) %>%
  filter(sum_count != 1)

all_richmond_with_pop %>%
  mutate(count = 1) %>%
  group_by(GISJOIN) %>%
  mutate(sum_count = sum(count)) %>%
  filter(sum_count != 1)

```

```{r merge data, include = FALSE}

# join with the final data set with the tracts and HOLC grades from all_holc_files_cleaning

# all_cities_grade_demo <- left_join(all_cities_tract_grades, race_1960_demo, by = "GISJOIN")

all_cities_grade_demo <- left_join(all_richmond_with_pop, race_1960_demo, by = "GISJOIN") %>%
  select(-STATE) %>%
  rename(demo_year = YEAR)

# NO DATA for Atlantic City from Census -> need to drop/drops
all_cities_grade_demo %>%
  filter(city == "Atlantic City")

```


```{r renaming relevant vars based on codebook to work with, include = FALSE}

# initialize data for analysis, and we will add on columns from the joined data for the variables we need 
data_for_analysis <- all_cities_grade_demo

# there are 4 cities being classified as Kansas City... WTF ... jk these codes are different - but still a concern that technically different cities based on census tract/nhgis
data_for_analysis %>%
  mutate(count = 1, n_NHGISCTY = as.numeric(NHGISCTY)) %>%
  group_by(n_NHGISCTY, NHGISST, city, state) %>%
  summarize(mean_NHGISCTY = mean(n_NHGISCTY)) %>%
  mutate(problem = ifelse(n_NHGISCTY != mean_NHGISCTY, 1, 0)) %>%
  filter(city == "Kansas City")


data_for_analysis %>%
  filter(city == "Atlantic City")
```

```{r}

# variable encodings in format: description (universe)

# Total persons (persons) - Using the data from the printed report because the race data is from the printed report and want to keep consistent source

data_for_analysis$tot_persons_printed <- all_cities_grade_demo$B53001


# RACE from printed report (Persons)

data_for_analysis$white_printed <- all_cities_grade_demo$B7B001
data_for_analysis$black_printed <- all_cities_grade_demo$B7B002
data_for_analysis$other_printed <- all_cities_grade_demo$B7B003

# total foreign stock from printed report (foreign stock persons)

data_for_analysis$foreign_stock_printed <- all_cities_grade_demo$B7M001

# foreign born (foreign stock persons)

data_for_analysis$foreign_born <- all_cities_grade_demo$B8J001


# School completed (persons 25 yr and over)

data_for_analysis$no_school <- all_cities_grade_demo$B8R001
data_for_analysis$school_yr_1_4 <- all_cities_grade_demo$B8R002
data_for_analysis$school_yr_5_7 <- all_cities_grade_demo$B8R003
data_for_analysis$school_yr_8 <- all_cities_grade_demo$B8R004
data_for_analysis$school_yr_hs_1_3 <- all_cities_grade_demo$B8R005
data_for_analysis$school_yr_hs_4 <- all_cities_grade_demo$B8R006
data_for_analysis$school_yr_college_1_3 <- all_cities_grade_demo$B8R007
data_for_analysis$school_yr_college_p <- all_cities_grade_demo$B8R008


# family income in 1959 (families)

data_for_analysis$fam_income_less_1k <- all_cities_grade_demo$B8W001
data_for_analysis$fam_income_1_2k <- all_cities_grade_demo$B8W002
data_for_analysis$fam_income_2_3k <- all_cities_grade_demo$B8W003
data_for_analysis$fam_income_3_4k <- all_cities_grade_demo$B8W004
data_for_analysis$fam_income_4_5k <- all_cities_grade_demo$B8W005
data_for_analysis$fam_income_5_6k <- all_cities_grade_demo$B8W006
data_for_analysis$fam_income_6_7k <- all_cities_grade_demo$B8W007
data_for_analysis$fam_income_7_8k <- all_cities_grade_demo$B8W008
data_for_analysis$fam_income_8_9k <- all_cities_grade_demo$B8W009
data_for_analysis$fam_income_9_10k <- all_cities_grade_demo$B8W010
data_for_analysis$fam_income_10_15k <- all_cities_grade_demo$B8W011
data_for_analysis$fam_income_15_25k <- all_cities_grade_demo$B8W012
data_for_analysis$fam_income_25k_p <- all_cities_grade_demo$B8W013


# Total Housing Units (h units)
data_for_analysis$tot_hunits <- all_cities_grade_demo$CA5001


# N owner occupied (occupied year round h units)
data_for_analysis$owner_occupied <- all_cities_grade_demo$B9O001

# N renter occupied (occupied year round h units)
data_for_analysis$renter_occupied <- all_cities_grade_demo$B9O002


# N vacant for rent (vacant year-round housing units)
data_for_analysis$vacant_for_rent<- all_cities_grade_demo$B8Q001
# N vacant for sale (vacant year-round housing units)
data_for_analysis$vacant_for_sale <- all_cities_grade_demo$B8Q002



# other type of vacancy status with other option
# N vacant for rent (vacant year-round housing units)
data_for_analysis$vacant_for_sale_2<- all_cities_grade_demo$B9R001
# N vacant for sale (vacant year-round housing units)
data_for_analysis$vacant_for_rent_2 <- all_cities_grade_demo$B9R002
# N vacant for sale (vacant year-round housing units)
data_for_analysis$vacant_other_2 <- all_cities_grade_demo$B9R003


# Occupied Units by Persons per Room (occupied units)
data_for_analysis$persons_per_room_half_or_less <- all_cities_grade_demo$B76001
data_for_analysis$persons_per_room_point51_point75 <- all_cities_grade_demo$B76002
data_for_analysis$persons_per_room_point76_one<- all_cities_grade_demo$B76003
data_for_analysis$persons_per_room_onepone_or_more <- all_cities_grade_demo$B76004


# Renter occupied units reporting rent
data_for_analysis$renter_occupied_units_reporting_rent <- all_cities_grade_demo$B8A001

# renter occupied unit aggregate monthly contract rent

data_for_analysis$agg_monthly_contract_rent <- all_cities_grade_demo$B8B001

# value of property from printed report (housing units)


data_for_analysis$property_value_u5k <- all_cities_grade_demo$B7O001
data_for_analysis$property_value_5000_7400 <- all_cities_grade_demo$B7O002
data_for_analysis$property_value_7500_9900 <- all_cities_grade_demo$B7O003
data_for_analysis$property_value_10000_12400 <- all_cities_grade_demo$B7O004
data_for_analysis$property_value_12500_14900 <- all_cities_grade_demo$B7O005
data_for_analysis$property_value_15000_17400 <- all_cities_grade_demo$B7O006
data_for_analysis$property_value_17500_19900 <- all_cities_grade_demo$B7O007
data_for_analysis$property_value_20000_24900 <- all_cities_grade_demo$B7O008
data_for_analysis$property_value_25000_34900 <- all_cities_grade_demo$B7O009
data_for_analysis$property_value_35000_plus <- all_cities_grade_demo$B7O010


# owner occupied units reporting value

data_for_analysis$owner_occ_property_value_u5k <- all_cities_grade_demo$CAO001
data_for_analysis$owner_occ_property_value_5000_7499 <- all_cities_grade_demo$CAO002
data_for_analysis$owner_occ_property_value_7500_9999 <- all_cities_grade_demo$CAO003
data_for_analysis$owner_occ_property_value_10000_12499 <- all_cities_grade_demo$CAO004
data_for_analysis$owner_occ_property_value_12500_14999 <- all_cities_grade_demo$CAO005
data_for_analysis$owner_occ_property_value_15000_17499 <- all_cities_grade_demo$CAO006
data_for_analysis$owner_occ_property_value_17500_19999 <- all_cities_grade_demo$CAO007
data_for_analysis$owner_occ_property_value_20000_24999 <- all_cities_grade_demo$CAO008
data_for_analysis$owner_occ_property_value_25000_34999 <- all_cities_grade_demo$CAO009
data_for_analysis$owner_occ_property_value_35000_plus <- all_cities_grade_demo$CAO010




# units in structure (housing units)

data_for_analysis$units_1 <- all_cities_grade_demo$B92001
data_for_analysis$units_2 <- all_cities_grade_demo$B92002
data_for_analysis$units_3_4 <- all_cities_grade_demo$B92003
data_for_analysis$units_5_9 <- all_cities_grade_demo$B92004
data_for_analysis$units_10_P <- all_cities_grade_demo$B92005


# year structure built (all housing units)

data_for_analysis$built_1950_1960 <- all_cities_grade_demo$B96001
data_for_analysis$built_1940_1949 <- all_cities_grade_demo$B96002
data_for_analysis$built_pre_1940 <- all_cities_grade_demo$B96003



# year head moved into household (occupied housing units)

data_for_analysis$moved_1958_1960 <- all_cities_grade_demo$CAJ001
data_for_analysis$moved_in_1954_1957 <- all_cities_grade_demo$CAJ002
data_for_analysis$moved_in_1940_1953 <- all_cities_grade_demo$CAJ003
data_for_analysis$moved_in_pre_1940 <- all_cities_grade_demo$CAJ004

# persons in group quarters from printed report (persons in hhs)

data_for_analysis$persons_group_quarters<- all_cities_grade_demo$B54001


# housing by condition

data_for_analysis$condition_sound <- all_cities_grade_demo$B67001
data_for_analysis$condition_deteriorated <- all_cities_grade_demo$B67002
data_for_analysis$condition_dilapidated <- all_cities_grade_demo$B67003

# employment status
data_for_analysis$employed_males <- data_for_analysis$B82001
data_for_analysis$unemployed_males <- data_for_analysis$B82002
data_for_analysis$armed_forces_males <- data_for_analysis$B82003
data_for_analysis$not_in_lf_males <- data_for_analysis$B82004
data_for_analysis$employed_females <- data_for_analysis$B82005
data_for_analysis$unemployed_females <- data_for_analysis$B82006
data_for_analysis$armed_forces_females <- data_for_analysis$B82007
data_for_analysis$not_in_lf_females<- data_for_analysis$B82008


# plumbing: DID NOT CODE ALL OPTIONS
data_for_analysis$plumbing_sound_w_all_facilities <- data_for_analysis$B9V001

data_for_analysis$plumbing_deteriorating_w_all_facilities <- data_for_analysis$B9V004
data_for_analysis$plumbing_deteriorating_lackorshare_hwater <- data_for_analysis$B9V005
data_for_analysis$plumbing_deteriorating_lackorshare_privatetoilet <- data_for_analysis$B9V006
data_for_analysis$plumbing_delapidated <- data_for_analysis$B9V007

# bathrooms
data_for_analysis$one_bathroom <- data_for_analysis$B9Y001
data_for_analysis$more_than_one_bathroom <- data_for_analysis$B9Y002
data_for_analysis$shared_or_no_inside_bathroom <- data_for_analysis$B9Y003


# rent buckets
data_for_analysis$contract_rent_lt_20 <- data_for_analysis$CAV001
data_for_analysis$contract_rent_20_29 <- data_for_analysis$CAV002
data_for_analysis$contract_rent_30_39 <- data_for_analysis$CAV003
data_for_analysis$contract_rent_40_49 <- data_for_analysis$CAV004
data_for_analysis$contract_rent_50_59 <- data_for_analysis$CAV005
data_for_analysis$contract_rent_60_69 <- data_for_analysis$CAV006
data_for_analysis$contract_rent_70_79 <- data_for_analysis$CAV007
data_for_analysis$contract_rent_80_89 <- data_for_analysis$CAV008
data_for_analysis$contract_rent_90_99 <- data_for_analysis$CAV009
data_for_analysis$contract_rent_l00_119 <- data_for_analysis$CAV010
data_for_analysis$contract_rent_120_149 <- data_for_analysis$CAV011
data_for_analysis$contract_rent_150p <- data_for_analysis$CAV012
data_for_analysis$contract_rent_no_cash_rent <- data_for_analysis$CAV013

# % African American
# % non-white
# % immigrants

# age of structure

# housing value

defined = c("B53001", "B7B001", "B7B002", "B7B003", "B7M001", "B8J001", "B8R001", 
            "B8R002", "B8R003", "B8R004", "B8R005", "B8R006", "B8R007", "B8R008",
            "B8W001", "B8W002", "B8W003", "B8W004", "B8W005", "B8W006", "B8W007",
            "B8W008", "B8W009", "B8W010", "B8W011", "B8W012", "B8W013", "CA5001",
            "B8F001", "B8F002", "B8Q001", "B8Q002", "B76001", "B76002", "B76003", 
            "B76004", "B8B001", "B7O001", "B7O002", "B7O003", "B7O004", "B7O005",
            "B7O006", "B7O007", "B7O008", "B7O009", "B7O010", "B92001", "B92002",
            "B92003", "B92004", "B92005", "B96001", "B96002", "B96003", "CAJ001",
            "CAJ002", "CAJ003", "CAJ004", "B54001", "B67001", "B67002", "B67003",
            "B9R001", "B9R002", "B9R003", "B8A001", "B82002", "B82003", "B82004",
            "B82005", "B82006", "B82007", "B82008", "B9V001", "B9V004", "B9V005",
            "B9V006", "B9V007", "B9Y001", "B9Y002", "B9Y003", "CAV001",
            "CAV002", "CAV003", "CAV004", "CAV005", "CAV006", "CAV007", "CAV008",
            "CAV009", "CAV010", "CAV011", "CAV012", "CAV013")


filtered <- data_for_analysis %>%
  select(!(defined))



```


```{r creating additional variables relevant for analysis, include = FALSE}

# calculate population density (originally in meters squared area so scale to km)
data_for_analysis$pop_density <- data_for_analysis$tot_persons_printed/data_for_analysis$tract_area * 1000000

# pct non-white
data_for_analysis$pct_non_white_printed <- (data_for_analysis$black_printed +
                                      data_for_analysis$other_printed)/data_for_analysis$tot_persons_printed * 100

# pct black
data_for_analysis$pct_black_printed <- (data_for_analysis$black_printed)/data_for_analysis$tot_persons_printed * 100


# % foreign stock
data_for_analysis$pct_foreign_stock_printed<- (data_for_analysis$foreign_stock_printed)/data_for_analysis$tot_persons_printed * 100

# % foreign born
data_for_analysis$pct_foreign_born <- (data_for_analysis$foreign_born)/data_for_analysis$tot_persons_printed * 100

# pct hs grads

# calculate total persons who have school data
data_for_analysis$tot_school_persons <- data_for_analysis$no_school + data_for_analysis$school_yr_1_4  +
  data_for_analysis$school_yr_5_7 + data_for_analysis$school_yr_8 + data_for_analysis$school_yr_hs_1_3 +
  data_for_analysis$school_yr_hs_4 + data_for_analysis$school_yr_college_1_3 +
  data_for_analysis$school_yr_college_p

# calculate total persons whose highest edu attainment is hs completion or greater
data_for_analysis$tot_hs_grads <- data_for_analysis$school_yr_hs_4 +
  data_for_analysis$school_yr_college_1_3 +
  data_for_analysis$school_yr_college_p

# calculate hs grads
data_for_analysis$pct_hs_grad <- data_for_analysis$tot_hs_grads/data_for_analysis$tot_school_persons * 100


# need to calculate income next -> how to choose something for this?? https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-poverty-people.html

# based on the above source, the pverty level for families of 3 in 1959 was 2,324 -> create indicator of below or above 3k income, roughly the poverty line for a family of 3. 

# average household size according to the census in 1960 was 3.29 https://www.census.gov/library/publications/1962/dec/pc-s1-23.html#:~:text=The%20number%20of%20households%20in,of%20household%20was%203.29%20persons.

# sum families with income in 1959 <3k and then divide by total # families


data_for_analysis$all_families_with_income_data <- data_for_analysis$fam_income_less_1k + data_for_analysis$fam_income_1_2k + data_for_analysis$fam_income_2_3k +
data_for_analysis$fam_income_3_4k + data_for_analysis$fam_income_4_5k + data_for_analysis$fam_income_5_6k +
data_for_analysis$fam_income_6_7k + data_for_analysis$fam_income_7_8k + data_for_analysis$fam_income_8_9k +
data_for_analysis$fam_income_9_10k + data_for_analysis$fam_income_10_15k + data_for_analysis$fam_income_15_25k +
data_for_analysis$fam_income_25k_p

data_for_analysis$all_families_with_income_lt_3k <- data_for_analysis$fam_income_less_1k + data_for_analysis$fam_income_1_2k + data_for_analysis$fam_income_2_3k 

data_for_analysis$pct_families_below_3k_income <- (data_for_analysis$all_families_with_income_lt_3k/
                                                     data_for_analysis$all_families_with_income_data) * 100

data_for_analysis$all_families_with_income_lt_4k <- data_for_analysis$fam_income_less_1k + data_for_analysis$fam_income_1_2k + data_for_analysis$fam_income_2_3k +
  data_for_analysis$fam_income_3_4k 

data_for_analysis$pct_families_below_4k_income <-   (data_for_analysis$all_families_with_income_lt_4k/
                                                     data_for_analysis$all_families_with_income_data) * 100 
# hhunits

# other type of vacancy status with other option
# N vacant for rent (vacant year-round housing units)
data_for_analysis$vacant_all <- data_for_analysis$vacant_for_rent_2 + data_for_analysis$vacant_for_sale_2 + 
  data_for_analysis$vacant_other_2

data_for_analysis$pct_vacant_all <- 100 * data_for_analysis$vacant_all/data_for_analysis$tot_hunits


# create var for occupied units which is all units minus vacant

data_for_analysis$occupied_units <- data_for_analysis$tot_hunits - data_for_analysis$vacant_all


# pct_owner_occupied out of all units
data_for_analysis$pct_owner_occupied <- 100 * data_for_analysis$owner_occupied/data_for_analysis$occupied_units


# pct renter occupied (occupied year round h units)
data_for_analysis$pct_renter_occupied <- 100 * data_for_analysis$renter_occupied/data_for_analysis$occupied_units


# pct units 1.01 or more people per room (highest category)
data_for_analysis$pct_one_point_0_one_people_per_room_or_more <- 100 *  data_for_analysis$persons_per_room_onepone_or_more/data_for_analysis$occupied_units


# average rent of owner occupied units
data_for_analysis$avg_monthly_contract_rent <- data_for_analysis$agg_monthly_contract_rent/ data_for_analysis$renter_occupied_units_reporting_rent

# data_for_analysis %>%  select(agg_monthly_contract_rent, renter_occupied_units_reporting_rent, avg_monthly_contract_rent, log_avg_monthly_contract_rent) %>% filter(avg_monthly_contract_rent > 300)

# data_for_analysis$avg_monthly_contract_rent[data_for_analysis$renter_occupied_units_reporting_rent == 0] <- NA
# data_for_analysis$avg_monthly_contract_rent[data_for_analysis$GISJOIN == 	"G08000100079" ] <- NA

data_for_analysis %>%
  filter(GISJOIN == 	"G08000100079" )




# log average rent of owner occupied units
data_for_analysis$log_avg_monthly_contract_rent <- log(data_for_analysis$avg_monthly_contract_rent)



# https://archive.curbed.com/2018/4/10/17219786/buying-a-house-mortgage-government-gi-bill says median home value was 11,900 in 1960

data_for_analysis$houses_w_property_value_data <- data_for_analysis$property_value_u5k +
  data_for_analysis$property_value_5000_7400 + data_for_analysis$property_value_7500_9900 +
  data_for_analysis$property_value_10000_12400 + data_for_analysis$property_value_12500_14900 +
  data_for_analysis$property_value_15000_17400 + data_for_analysis$property_value_17500_19900 +
  data_for_analysis$property_value_20000_24900 + data_for_analysis$property_value_25000_34900 +
  data_for_analysis$property_value_35000_plus


# weighted property value

data_for_analysis$weighted_prop_value <- (data_for_analysis$property_value_u5k * 2500 +
                                                  data_for_analysis$property_value_5000_7400 * 6250  + 
                                                  data_for_analysis$property_value_7500_9900 * 8750 +
                                                  data_for_analysis$property_value_10000_12400 * 11250 + 
                                                  data_for_analysis$property_value_12500_14900 * ((15000-12500)/2 + 12500) +
                                                  data_for_analysis$property_value_15000_17400 * ((17500-15000)/2 + 15000) + 
                                                  data_for_analysis$property_value_17500_19900 * ((20000-17500)/2 + 17500) +
                                                  data_for_analysis$property_value_20000_24900 * ((25000-20000)/2 + 20000) + 
                                                  data_for_analysis$property_value_25000_34900 * ((35000-25000)/2 + 25000) +
                                                  data_for_analysis$property_value_35000_plus* (35000))/ data_for_analysis$houses_w_property_value_data

# percent of houses of value under 5k

data_for_analysis$pct_houses_w_property_value_u5k <- 100* data_for_analysis$property_value_u5k/data_for_analysis$houses_w_property_value_data



# owner occupied units reporting value

data_for_analysis$owner_occ_property_value_u5k <- all_cities_grade_demo$CAO001
data_for_analysis$owner_occ_property_value_5000_7499 <- all_cities_grade_demo$CAO002
data_for_analysis$owner_occ_property_value_7500_9999 <- all_cities_grade_demo$CAO003
data_for_analysis$owner_occ_property_value_10000_12499 <- all_cities_grade_demo$CAO004
data_for_analysis$owner_occ_property_value_12500_14999 <- all_cities_grade_demo$CAO005
data_for_analysis$owner_occ_property_value_15000_17499 <- all_cities_grade_demo$CAO006
data_for_analysis$owner_occ_property_value_17500_19999 <- all_cities_grade_demo$CAO007
data_for_analysis$owner_occ_property_value_20000_24999 <- all_cities_grade_demo$CAO008
data_for_analysis$owner_occ_property_value_25000_34999 <- all_cities_grade_demo$CAO009
data_for_analysis$owner_occ_property_value_35000_plus <- all_cities_grade_demo$CAO010


data_for_analysis$tot_owner_occ_with_value = data_for_analysis$owner_occ_property_value_u5k + data_for_analysis$owner_occ_property_value_5000_7499 + data_for_analysis$owner_occ_property_value_7500_9999 + data_for_analysis$owner_occ_property_value_10000_12499 + data_for_analysis$owner_occ_property_value_12500_14999  + data_for_analysis$owner_occ_property_value_15000_17499 + data_for_analysis$owner_occ_property_value_17500_19999 + data_for_analysis$owner_occ_property_value_20000_24999 + data_for_analysis$owner_occ_property_value_25000_34999 + data_for_analysis$owner_occ_property_value_35000_plus 

data_for_analysis$owner_occ_property_value = (data_for_analysis$owner_occ_property_value_u5k * 2500 + 
                                                data_for_analysis$owner_occ_property_value_5000_7499 * 6250 +
                                                data_for_analysis$owner_occ_property_value_7500_9999 * 8750 +
                                                data_for_analysis$owner_occ_property_value_10000_12499 * 11250 +
                                                data_for_analysis$owner_occ_property_value_12500_14999 * ((15000-12500)/2 + 12500)  +
                                                data_for_analysis$owner_occ_property_value_15000_17499 * ((17500-15000)/2 + 15000) +
                                                data_for_analysis$owner_occ_property_value_17500_19999 * ((20000-17500)/2 + 17500) +
                                                data_for_analysis$owner_occ_property_value_20000_24999 * ((25000-20000)/2 + 20000) +
                                                data_for_analysis$owner_occ_property_value_25000_34999 * ((35000-25000)/2 + 25000) +
                                                data_for_analysis$owner_occ_property_value_35000_plus * 35000)/data_for_analysis$tot_owner_occ_with_value



# pct 1 unit houses
data_for_analysis$units_with_unit_data <- data_for_analysis$units_1 + data_for_analysis$units_2 + data_for_analysis$units_3_4 + data_for_analysis$units_5_9 + data_for_analysis$units_10_P
data_for_analysis$pct_single_unit <- data_for_analysis$units_1/data_for_analysis$units_with_unit_data * 100

# pct built pre 1940

data_for_analysis$pct_built_pre_1940 <- data_for_analysis$built_pre_1940/(data_for_analysis$built_1950_1960 + data_for_analysis$built_1940_1949 + data_for_analysis$built_pre_1940) * 100



# year head moved into household (occupied housing units)

data_for_analysis$pct_moved_pre_1940 <- data_for_analysis$moved_in_pre_1940/(data_for_analysis$moved_1958_1960 + data_for_analysis$moved_in_1954_1957 + data_for_analysis$moved_in_1940_1953 + data_for_analysis$moved_in_pre_1940) * 100

data_for_analysis$pct_moved_1958_1960 <- data_for_analysis$moved_1958_1960/(data_for_analysis$moved_1958_1960 + data_for_analysis$moved_in_1954_1957 + data_for_analysis$moved_in_1940_1953 + data_for_analysis$moved_in_pre_1940) * 100

# pct_pop group quarters

data_for_analysis$pct_persons_group_quarters <- 100 * data_for_analysis$persons_group_quarters/data_for_analysis$tot_persons_printed

# CONDITION

# housing by condition: pct deteriorated or dilapidated

data_for_analysis$pct_housing_deteriorated_dilap <- (data_for_analysis$condition_deteriorated + data_for_analysis$condition_dilapidated)/ (data_for_analysis$condition_sound + data_for_analysis$condition_deteriorated + data_for_analysis$condition_dilapidated) * 100


data_for_analysis %>%
  ggplot(aes(x = pct_housing_deteriorated_dilap, y = prop_grade_D)) +
  geom_point() +
  geom_smooth()

# pct males unemployed

data_for_analysis$pct_unemployed_males <- 100 * data_for_analysis$unemployed_males/
  (data_for_analysis$unemployed_males + data_for_analysis$employed_males
   + data_for_analysis$armed_forces_males + data_for_analysis$not_in_lf_males)  


# plumbing: pct deteriorating or dilapidated
data_for_analysis$pct_plumbing_detdilap <- 100 * (data_for_analysis$plumbing_deteriorating_w_all_facilities  +
  data_for_analysis$plumbing_deteriorating_lackorshare_hwater +
  data_for_analysis$plumbing_deteriorating_lackorshare_privatetoilet +
  data_for_analysis$plumbing_delapidated )/data_for_analysis$tot_hunits

# bathrooms

data_for_analysis$pct_shared_or_bath_outside <- data_for_analysis$shared_or_no_inside_bathroom/ data_for_analysis$tot_hunits * 100
data_for_analysis$pct_more_than_one_bathroom <- data_for_analysis$more_than_one_bathroom/data_for_analysis$tot_hunits * 100


# rent buckets
data_for_analysis$contract_rent_lt_20 <- data_for_analysis$CAV001
data_for_analysis$contract_rent_20_29 <- data_for_analysis$CAV002
data_for_analysis$contract_rent_30_39 <- data_for_analysis$CAV003
data_for_analysis$contract_rent_40_49 <- data_for_analysis$CAV004
data_for_analysis$contract_rent_50_59 <- data_for_analysis$CAV005
data_for_analysis$contract_rent_60_69 <- data_for_analysis$CAV006
data_for_analysis$contract_rent_70_79 <- data_for_analysis$CAV007
data_for_analysis$contract_rent_80_89 <- data_for_analysis$CAV008
data_for_analysis$contract_rent_90_99 <- data_for_analysis$CAV009
data_for_analysis$contract_rent_l00_119 <- data_for_analysis$CAV010
data_for_analysis$contract_rent_120_149 <- data_for_analysis$CAV011
data_for_analysis$contract_rent_150p <- data_for_analysis$CAV012
data_for_analysis$contract_rent_no_cash_rent <- data_for_analysis$CAV013

all_houses_reporting_contract_rent <- sum(data_for_analysis$contract_rent_lt_20, na.rm = T) + sum(data_for_analysis$contract_rent_20_29, na.rm = T) +
  sum(data_for_analysis$contract_rent_30_39, na.rm = T) + sum(data_for_analysis$contract_rent_40_49 , na.rm = T) + 
  sum(data_for_analysis$contract_rent_50_59, na.rm = T) + sum(data_for_analysis$contract_rent_60_69, na.rm = T) +
  sum(data_for_analysis$contract_rent_70_79, na.rm = T) + sum(data_for_analysis$contract_rent_80_89 , na.rm = T) + 
  sum(data_for_analysis$contract_rent_90_99, na.rm = T) + sum(data_for_analysis$contract_rent_l00_119, na.rm = T) + 
  sum(data_for_analysis$contract_rent_120_149, na.rm = T) + sum(data_for_analysis$contract_rent_150p, na.rm = T) +
  sum(data_for_analysis$contract_rent_no_cash_rent, na.rm = T)
  

.25 * all_houses_reporting_contract_rent 

sum(data_for_analysis$contract_rent_lt_20, na.rm = T) + sum(data_for_analysis$contract_rent_20_29, na.rm = T) + sum(data_for_analysis$contract_rent_30_39, na.rm = T) + sum(data_for_analysis$contract_rent_40_49 , na.rm = T)

# pct with rent < $50 (approximately 25 percentile of rent)

data_for_analysis$pct_contract_rent_lt_50 <- 100 * (data_for_analysis$contract_rent_lt_20 + data_for_analysis$contract_rent_20_29 + data_for_analysis$contract_rent_30_39
                                              + data_for_analysis$contract_rent_40_49)/(data_for_analysis$contract_rent_lt_20 + data_for_analysis$contract_rent_20_29 +
                                                                                          data_for_analysis$contract_rent_30_39 + data_for_analysis$contract_rent_40_49 +
                                                                                          data_for_analysis$contract_rent_50_59 + data_for_analysis$contract_rent_60_69 +
                                                                                          data_for_analysis$contract_rent_70_79 + data_for_analysis$contract_rent_80_89 +
                                                                                          data_for_analysis$contract_rent_90_99 + data_for_analysis$contract_rent_l00_119 +
                                                                                          data_for_analysis$contract_rent_120_149 + data_for_analysis$contract_rent_150p)
# number of units reporting cash rent
data_for_analysis$reporting_contract_rent_calc <- data_for_analysis$contract_rent_lt_20 + data_for_analysis$contract_rent_20_29 +
                                                                                          data_for_analysis$contract_rent_30_39 + data_for_analysis$contract_rent_40_49 +
                                                                                          data_for_analysis$contract_rent_50_59 + data_for_analysis$contract_rent_60_69 +
                                                                                          data_for_analysis$contract_rent_70_79 + data_for_analysis$contract_rent_80_89 +
                                                                                          data_for_analysis$contract_rent_90_99 + data_for_analysis$contract_rent_l00_119 +
                                                                                          data_for_analysis$contract_rent_120_149 + data_for_analysis$contract_rent_150p

# weighted contract rent: 150+ coded as 150
data_for_analysis$weighted_cash_contract_rent <- (data_for_analysis$contract_rent_lt_20 * 10 + data_for_analysis$contract_rent_20_29  * 24.5 + 
  data_for_analysis$contract_rent_30_39 * 34.5 + data_for_analysis$contract_rent_40_49 * 44.5 + data_for_analysis$contract_rent_50_59 * 54.5 +
  data_for_analysis$contract_rent_60_69 * 64.5 + data_for_analysis$contract_rent_70_79 * 74.5 + data_for_analysis$contract_rent_80_89 * 84.5 +
  data_for_analysis$contract_rent_90_99 * 94.5 + data_for_analysis$contract_rent_l00_119 * 109.5 + data_for_analysis$contract_rent_120_149 * 134.5 +
  data_for_analysis$contract_rent_150p * 150)/data_for_analysis$reporting_contract_rent_calc

data_for_analysis$weighted_cash_contract_rent_lt_50 <- ifelse(data_for_analysis$weighted_cash_contract_rent < 50, 1, 0)


colnames(data_for_analysis)

data_for_analysis <- data_for_analysis %>%
  select(NHGISST:AREANAME, tot_persons_printed:weighted_cash_contract_rent_lt_50)

colnames(data_for_analysis)

data_for_analysis %>%
  ggplot(aes(x = weighted_cash_contract_rent)) +
  geom_histogram()

```

```{r}
data_for_analysis %>%
  ggplot(aes(x = weighted_prop_value)) +
  geom_histogram()

summary(data_for_analysis$weighted_prop_value)
```

```{r eval = FALSE}

data_for_analysis  %>%
  ggplot(aes(x = pct_families_below_4k_income)) +
  geom_histogram(bins = 100) 


data_for_analysis  %>%
  ggplot(aes(x = pct_families_below_4k_income , y= prop_grade_D)) +
  geom_point() +
  geom_smooth(se = FALSE, method = "lm")


data_for_analysis %>%
  filter(pct_contract_rent_lt_50 < 1, prop_grade_D > .2) %>%
  select(1:10, tot_hunits, avg_monthly_contract_rent, pct_families_below_3k_income, pct_contract_rent_lt_50, contract_rent_lt_20, contract_rent_20_29, contract_rent_30_39, contract_rent_40_49, contract_rent_50_59, contract_rent_60_69, contract_rent_70_79, contract_rent_80_89, contract_rent_90_99, contract_rent_l00_119, contract_rent_120_149, 
         contract_rent_no_cash_rent)

```

```{r eval = FALSE}
data_for_analysis  %>%
  ggplot(aes(x = pct_contract_rent_lt_50 , y= prop_grade_D)) +
  geom_point() +
  geom_smooth(se = FALSE, method = "lm")
```

```{r eval = FALSE}
data_for_analysis  %>%
  ggplot(aes(x = weighted_cash_contract_rent , y= prop_grade_D)) +
  geom_point() +
  geom_smooth(se = FALSE, method = "lm")
```


```{r eval = FALSE}

data_for_analysis  %>%
  ggplot(aes(x = weighted_cash_contract_rent_lt_50 , y= prop_grade_D)) +
  geom_point() +
  geom_smooth(se = FALSE, method = "lm")

```

```{r, eval = FALSE}


data_for_analysis  %>%
  ggplot(aes(x = pct_families_below_3k_income, y= prop_grade_D)) +
  geom_jitter() +
  geom_smooth(se = FALSE, method = "lm")

data_for_analysis  %>%
  ggplot(aes(x = pct_families_below_3k_income)) +
  geom_histogram(bins = 100)

data_for_analysis  %>%
  filter(avg_monthly_contract_rent > 5) %>%
  ggplot(aes(x = avg_monthly_contract_rent, y= prop_grade_D)) +
  geom_jitter() +
  geom_smooth(se = FALSE)
  
  
```



```{r eval = FALSE}
all_cities_grade_demo  %>%
  ggplot(aes(x = pct_, y= rounded_tract_holc_grade)) +
  geom_point() +
  geom_smooth(se = FALSE)
```

```{r export data, include = FALSE}
#write.csv(all_cities_grade_demo, "all_cities_grade_demo.csv")

data_for_analysis$pct_d_of_accounted_for<- data_for_analysis$prop_D_of_accounted_for * 100
data_for_analysis$pct_grade_d <- data_for_analysis$prop_grade_D * 100


# drop 	GISJOIN = G2500250SC0003 in treatment group because major denominator, tot_hunits missing/0 and others where 0
data_for_analysis <- data_for_analysis %>%
  #filter(GISJOIN != "G2500250SC0003")
  filter(tot_hunits != 0)

# data_for_analysis %>% filter(tot_persons_printed == 0)

write.csv(data_for_analysis, "data_for_analysis.csv")

colnames(data_for_analysis)

data_for_analysis %>%
  filter(city == "Fort Worth")
```


```{r eval = FALSE}
summary <- data_for_analysis %>%
  filter(area_accounted_for >= .5 ) %>%
  mutate(over_50p_red = ifelse(pct_grade_d > 50, 1, 0),
         over_75p_red = ifelse(pct_grade_d > 75, 1, 0),
         over_90p_red = ifelse(pct_grade_d > 90, 1, 0))


mean(summary$over_50p_red)
mean(summary$over_75p_red)
mean(summary$over_90p_red)



data_for_analysis  %>%
  ggplot(aes(x = area_accounted_for, y= prop_grade_D)) +
  geom_jitter() +
  geom_smooth(se = FALSE, method = "lm")

summary  %>%
  filter(area_accounted_for > .50) %>%
  ggplot(aes(x = pct_grade_d)) +
  geom_histogram(bins = 100)

# histogram of citypop for all data
data_for_analysis %>%
  group_by(city, state, citypop_total) %>%
  summarise(mean_city_pop = mean(citypop_total)) %>%
  ggplot(aes(mean_city_pop)) +
  geom_histogram(bins = 100) +
  geom_vline(xintercept = 30000, color = "red") +
  geom_vline(xintercept = 50000, color = "red") +
  ggtitle("Distribution of City Populations Represented in the Data") +
  labs(caption = "Red lines at 30,000 and 50,000 enclose the cities in the treatment and control groups, a small proportion of the data.") +
  theme(plot.caption = element_text(hjust = 0))

# histogram of area covered for all data
data_for_analysis %>%
  ggplot(aes(area_accounted_for)) +
  geom_histogram(bins = 100) +
  geom_vline(xintercept = .5, color = "red") +
  geom_vline(xintercept = .75, color = "red") +
  geom_vline(xintercept = .9, color = "red") +
  coord_cartesian(xlim = c(0,1)) +
  ggtitle("Distribution Census Tract Area Accounted for by HOLC Graded Areas in the Data") +
  #labs(caption = "Red lines at 30,000 and 50,000 enclose the cities in the treatment and control groups, a small proportion of the data.") +
  theme(plot.caption = element_text(hjust = 0))

# histogram of area covered for all data
data_for_analysis %>%
  ggplot(aes(pct_grade_d)) +
  geom_histogram(bins = 100) +
  geom_vline(xintercept = 50, color = "red") +
  geom_vline(xintercept = 75, color = "red") +
  geom_vline(xintercept = 90, color = "red") +
  coord_cartesian(xlim = c(0,100)) +
  ggtitle("Distribution of Pct. Census Tract Area Covered by HOLC D/Red Graded Areas") +
  #labs(caption = "Red lines at 30,000 and 50,000 enclose the cities in the treatment and control groups, a small proportion of the data.") +
  theme(plot.caption = element_text(hjust = 0))

summaries <- data_for_analysis %>%
  mutate(count = 1) %>%
  group_by(city, state) %>%
  summarise(sum_n = sum(count))

mean(summaries$sum_n)

data_for_analysis %>%
  filter(citypop_total < 60000, citypop_total > 40000) %>%
  mutate(count = 1) %>%
  group_by(state, city) %>%
  summarise(sum_n = sum(count))

data_for_analysis %>%
  filter(citypop_total <= 50000, citypop_total >= 40000, area_accounted_for >= .5,
         tot_hunits == 0)


treatment_group <- data_for_analysis %>%
  filter(citypop_total <= 50000, citypop_total >= 40000, area_accounted_for >= .5) %>%
  select(NHGISST:citypop_total, pct_non_white_printed: pct_grade_d)

colnames(treatment_group)


# histogram of area covered for all data
data_for_analysis %>%
  filter(area_accounted_for >= .5, citypop_total > 60000) %>%
  ggplot(aes(pct_grade_d)) +
  geom_histogram(bins = 100) +
  geom_vline(xintercept = 50, color = "red") +
  geom_vline(xintercept = 75, color = "red") +
  geom_vline(xintercept = 90, color = "red") +
  coord_cartesian(xlim = c(0,100)) +
  ggtitle("Distribution of Pct. Census Tract Area Covered by HOLC D/Red Graded Areas") +
  #labs(caption = "Red lines at 30,000 and 50,000 enclose the cities in the treatment and control groups, a small proportion of the data.") +
  theme(plot.caption = element_text(hjust = 0))

data_for_analysis

data_for_analysis %>% 
  filter(area_accounted_for >= .5, citypop_total > 60000) %>% 
  summarise(mean_d = mean(pct_grade_d, na.rm = T),
            var_d = var(pct_grade_d, na.rm = T))




```

```{r}
data_for_analysis %>% filter(city == "Kansas City")
```


```{r}
data_for_analysis %>%
  filter(citypop_total <= 60000, citypop_total >= 40000)  %>%
  mutate(count = 1) %>%
  group_by(city, state, citypop_total, CITY_old) %>%
  summarise(tracts = sum(count)) %>%
  view()
  

data_for_analysis %>%
  filter(GISJOIN == "G01007300016")
  
```

```{r}

# final data for predictions has 13,073 rows

data_for_analysis %>%
  mutate(count = 1) %>%
  group_by(GISJOIN) %>%
  mutate(sum_count = sum(count)) %>%
  filter(sum_count != 1)

city_old_codes <- data_for_analysis %>%
  group_by(city, state, CITY_old) %>%
  select(city, state, CITY_old) %>%
  unique()

write.csv(city_old_codes, "ipums_city_codes_city_state.csv")

```


```{r some cleaning now that we are merging with future years}
data_for_analysis_recode <- data_for_analysis %>%
  select(nhgisst_1960 = NHGISST,
         nhgiscty_1960 = NHGISCTY,
         gisjoin_1960 = GISJOIN,
         holc_city = city,
         holc_state = state,
         citypop_1930 = citypop_total,
         tract_area_1960 = tract_area,
         area_accounted_for_1960 = area_accounted_for,
         pct_grade_d,
         prop_grade_D:prop_grade_A_B,
         tot_persons_printed_1960 = tot_persons_printed,
         pop_density_1960 = pop_density,
         pct_non_white_1960 = pct_non_white_printed,
         pct_black_1960 = pct_black_printed,
         pct_foreign_born_1960 = pct_foreign_born,
         pct_hs_grad_1960 = pct_hs_grad,
         pct_vacant_1960 = pct_vacant_all,
         pct_owner_occupied_1960 = pct_owner_occupied,
         pct_renter_occupied_1960 = pct_renter_occupied,
         pct_one_point_0_one_people_per_room_or_more_1960 = pct_one_point_0_one_people_per_room_or_more,
         avg_monthly_contract_rent_1960 = avg_monthly_contract_rent,
         weighted_prop_value_1960 = weighted_prop_value,
         pct_single_unit_1960 = pct_single_unit,
         pct_housing_deteriorated_dilap_1960 = pct_housing_deteriorated_dilap,
         pct_unemployed_males_1960 = pct_unemployed_males,
         pct_more_than_one_bathroom_1960 = pct_more_than_one_bathroom,
         pct_contract_rent_lt_50_1960 = pct_contract_rent_lt_50,
         weighted_cash_contract_rent_1960 = weighted_cash_contract_rent) %>%
  mutate(log_property_value_1960 = log(weighted_prop_value_1960),
         log_contract_rent_1960 = log(weighted_cash_contract_rent_1960))


write.csv(data_for_analysis_recode, "data_for_analysis_recode.csv")

colnames(data_for_analysis_recode)
  
```

