---
title: "Selected Tract Census FInal Data Merge"
author: "Maria Burzillo"
date: "2/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

```{r load data}

# load demographic data that contains all potential variables
nhgis0023_ds92_1960_tract <- read_csv("Demographic Data/1960 All Vars/nhgis0023_csv/nhgis0023_ds92_1960_tract.csv")

# load demographic data that contains housing add on variables to look at land rents
housing_add_on_1960_tract <- read_csv("Demographic Data/1960 All Vars/1960 Housing Add-On/nhgis0035_ds92_1960_tract.csv")

potential_treatment <- read_csv("selected_treatment.csv") %>%
  select(-wkt_geom, -YEAR) %>%
  mutate(treatment = factor(1)) %>%
  rename(state = STATE,
         cityname = NAME,
         intersect_area = area,
         tract_area = SHAPE_AREA)

potential_control <- read_csv("potential_control.csv") %>%
  select(-wkt_geom, -YEAR) %>%
  mutate(treatment = factor(0)) %>%
  rename(state = STATE,
         cityname = NAME,
         intersect_area = area,
         tract_area = SHAPE_AREA)

state_abs <- read_csv("50_us_states_all_data.csv")

growth_rate_radii_data <- read_excel("treatment_control_growth_rate.xlsx") %>%
  select(-treatment)

# hard code these names again because issue with space in spelling from original data source causing join to fail
growth_rate_radii_data$city[growth_rate_radii_data$citypop_1990 == 783362] <- "San Jose"
growth_rate_radii_data$city[growth_rate_radii_data$citypop_1990 == 57835] <- "Port Arthur"
growth_rate_radii_data$city[growth_rate_radii_data$citypop_1990 == 84782	] <- "San Angelo"
growth_rate_radii_data$city[growth_rate_radii_data$citypop_1990 == 85679] <- "Santa Barbara"
growth_rate_radii_data$city[growth_rate_radii_data$citypop_1990 == 69990] <- "High Point"
growth_rate_radii_data$city[growth_rate_radii_data$citypop_1990 == 97038] <- "Green Bay"
growth_rate_radii_data$city[growth_rate_radii_data$citypop_1990 == 283308] <- "Colorado Springs"
growth_rate_radii_data$city[growth_rate_radii_data$citypop_1990 == 110432] <- "Ann Arbor"
growth_rate_radii_data$city[growth_rate_radii_data$citypop_1990 == 222684] <- "Baton Rouge"
growth_rate_radii_data$city[growth_rate_radii_data$citypop_1990 == 258933] <- "Corpus Christi"
growth_rate_radii_data$city[growth_rate_radii_data$citypop_1990 == 72798] <- "Fort Smith"


# import csv with 1940 city data from ipums for hh observations and person level obs
ipums_1940_hh_level <- read_csv("1930 - 1940 City Population Data/city_1940_ipums_hh_level_summary.csv")

ipums_1940_person_level <- read_csv("1930 - 1940 City Population Data/city_1940_ipums_person_level_summary.csv")


# load region state_ab correspondence

state_ab_region <- read_csv("state_ab_region.csv")

# import land residuals data

land_residuals <- read_csv("Demographic Data/land_rent_value_resid.csv")
```

```{r joining tract data, demo data, and city population data}

# join treatment and control to get one dataset
potential_tracts <- rbind(potential_control, potential_treatment)  %>%
  unique


# take relevant columns from city pop data
city_names_pops_1930 <- ipums_1930_cities_by_pop_full_sample %>%
  select(cityname, state, citypop_total_1930 = citypop_total, numeric_city_code = city)

city_names_pops_1930 <- left_join(city_names_pops_1930, state_abs, by = c("state" = "state_ab")) %>%
  rename(state_ab = state, state = state.y)

# join with radii and growth rate data
city_names_pops_growth <- left_join(city_names_pops_1930, growth_rate_radii_data, by = c("cityname" = "city", "state_ab" = "state", "citypop_total_1930" = "citypop_total_1930"))

# prepare to join the 1940 city level ipums data
ipums_1940_city <- full_join(ipums_1940_hh_level, ipums_1940_person_level) %>%
  select(
    city,
    city_hh_1940 = hhwt,
    citypop_1940 = perwt,
    city_1940_pct_owner_occ_non_v = pct_owner_occupied_non_vacant,
    city_1940_avg_contract_rent = avg_contract_rent,
    city_1940_pct_contract_rent_lt_50 = pct_contract_rent_lt_50,
    city_1940_avg_h_value_ = avg_house_value_hhwt,
    city_1940_pct_unemp_males_14_plus = pct_unemp_males_14_plus,
    city_1940_pct_emp_males_14_plus = pct_emp_males_14_plus,
    city_1940_avg_wage_emp_males_14_p = avg_wage_emp_males_14_p,
    city_1940_pct_black = pct_black_perwt,
    city_1940_pct_completed_hs = pct_completed_hs,
    city_1940_pct_completed_hs_male_18_64 = pct_completed_hs_male_18_64,
    city_1940_pct_all_males_18_64_employed = pct_all_males_18_64_employed,
    city_1940_pct_all_males_14_plus_employed = pct_all_males_14_plus_emp,
    city_1940_pct_completed_hs_25_plus = pct_completed_hs_25_plus
  )

city_names_pops_growth_ipums <- left_join(city_names_pops_growth,ipums_1940_city, by = c("numeric_city_code" = "city") )



potential_tracts_demo <- left_join(potential_tracts, city_names_pops_growth_ipums, by = c("cityname" = "cityname", "state" = "state"))

# join with the demographic data
potential_tracts_demo <- left_join(potential_tracts_demo, nhgis0023_ds92_1960_tract, by = "GISJOIN") 

city_treatment_status <- potential_tracts_demo %>%
  select(treatment, numeric_city_code) %>%
  unique()

write.csv(city_treatment_status, "city_treatment_status.csv")

```



```{r OLD - use if restricting within radius, eval = FALSE}
# this actually doesn't do anything because it seems like everything intersected correctly
treatment_within_r <- treatment_demo %>%
  group_by(STATE.x, PLACE, GISJOIN) %>%
  summarise(tot_area_intersecting = sum(area),
            prop_within_radius = tot_area_intersecting/SHAPE_AREA,
            within_r = ifelse(prop_within_radius == 1, 1, 0),
            within_r_75 = ifelse(prop_within_radius >= .75, 1, 0),
            within_r_50 = ifelse(prop_within_radius >= .50, 1, 0))


# 404 tracts completely inside radii
sum(treatment_within_r$within_r)
# 588 75% within
sum(treatment_within_r$within_r_75)
# 644 50% within
sum(treatment_within_r$within_r_50)
```

```{r renaming relevant census variables, include = FALSE}
# variable encodings in format: description (universe)

# Total persons (persons) - Using the data from the printed report because the race data is from the printed report and want to keep consistent source

potential_tracts_demo$tot_persons_printed <- potential_tracts_demo$B53001


# RACE from printed report (Persons)

potential_tracts_demo$white_printed <- potential_tracts_demo$B7B001
potential_tracts_demo$black_printed <- potential_tracts_demo$B7B002
potential_tracts_demo$other_printed <- potential_tracts_demo$B7B003

# total foreign stock from printed report (foreign stock persons)

potential_tracts_demo$foreign_stock_printed <- potential_tracts_demo$B7M001

# foreign born (foreign stock persons)

potential_tracts_demo$foreign_born <- potential_tracts_demo$B8J001


# School completed (persons 25 yr and over)

potential_tracts_demo$no_school <- potential_tracts_demo$B8R001
potential_tracts_demo$school_yr_1_4 <- potential_tracts_demo$B8R002
potential_tracts_demo$school_yr_5_7 <- potential_tracts_demo$B8R003
potential_tracts_demo$school_yr_8 <- potential_tracts_demo$B8R004
potential_tracts_demo$school_yr_hs_1_3 <- potential_tracts_demo$B8R005
potential_tracts_demo$school_yr_hs_4 <- potential_tracts_demo$B8R006
potential_tracts_demo$school_yr_college_1_3 <- potential_tracts_demo$B8R007
potential_tracts_demo$school_yr_college_p <- potential_tracts_demo$B8R008


# family income in 1959 (families)

potential_tracts_demo$fam_income_less_1k <- potential_tracts_demo$B8W001
potential_tracts_demo$fam_income_1_2k <- potential_tracts_demo$B8W002
potential_tracts_demo$fam_income_2_3k <- potential_tracts_demo$B8W003
potential_tracts_demo$fam_income_3_4k <- potential_tracts_demo$B8W004
potential_tracts_demo$fam_income_4_5k <- potential_tracts_demo$B8W005
potential_tracts_demo$fam_income_5_6k <- potential_tracts_demo$B8W006
potential_tracts_demo$fam_income_6_7k <- potential_tracts_demo$B8W007
potential_tracts_demo$fam_income_7_8k <- potential_tracts_demo$B8W008
potential_tracts_demo$fam_income_8_9k <- potential_tracts_demo$B8W009
potential_tracts_demo$fam_income_9_10k <- potential_tracts_demo$B8W010
potential_tracts_demo$fam_income_10_15k <- potential_tracts_demo$B8W011
potential_tracts_demo$fam_income_15_25k <- potential_tracts_demo$B8W012
potential_tracts_demo$fam_income_25k_p <- potential_tracts_demo$B8W013


# Total Housing Units (h units)
potential_tracts_demo$tot_hunits <- potential_tracts_demo$CA5001


# N owner occupied (occupied year round h units)
potential_tracts_demo$owner_occupied <- potential_tracts_demo$B9O001

# N renter occupied (occupied year round h units)
potential_tracts_demo$renter_occupied <- potential_tracts_demo$B9O002


# N vacant for rent (vacant year-round housing units)
potential_tracts_demo$vacant_for_rent<- potential_tracts_demo$B8Q001
# N vacant for sale (vacant year-round housing units)
potential_tracts_demo$vacant_for_sale <- potential_tracts_demo$B8Q002



# other type of vacancy status with other option
# N vacant for rent (vacant year-round housing units)
potential_tracts_demo$vacant_for_sale_2<- potential_tracts_demo$B9R001
# N vacant for sale (vacant year-round housing units)
potential_tracts_demo$vacant_for_rent_2 <- potential_tracts_demo$B9R002
# N vacant for sale (vacant year-round housing units)
potential_tracts_demo$vacant_other_2 <- potential_tracts_demo$B9R003


# Occupied Units by Persons per Room (occupied units)
potential_tracts_demo$persons_per_room_half_or_less <- potential_tracts_demo$B76001
potential_tracts_demo$persons_per_room_point51_point75 <- potential_tracts_demo$B76002
potential_tracts_demo$persons_per_room_point76_one<- potential_tracts_demo$B76003
potential_tracts_demo$persons_per_room_onepone_or_more <- potential_tracts_demo$B76004


# Renter occupied units reporting rent
potential_tracts_demo$renter_occupied_units_reporting_rent <- potential_tracts_demo$B8A001

# renter occupied unit aggregate monthly contract rent

potential_tracts_demo$agg_monthly_contract_rent <- potential_tracts_demo$B8B001

# value of property from printed report (housing units)


potential_tracts_demo$property_value_u5k <- potential_tracts_demo$B7O001
potential_tracts_demo$property_value_5000_7400 <- potential_tracts_demo$B7O002
potential_tracts_demo$property_value_7500_9900 <- potential_tracts_demo$B7O003
potential_tracts_demo$property_value_10000_12400 <- potential_tracts_demo$B7O004
potential_tracts_demo$property_value_12500_14900 <- potential_tracts_demo$B7O005
potential_tracts_demo$property_value_15000_17400 <- potential_tracts_demo$B7O006
potential_tracts_demo$property_value_17500_19900 <- potential_tracts_demo$B7O007
potential_tracts_demo$property_value_20000_24900 <- potential_tracts_demo$B7O008
potential_tracts_demo$property_value_25000_34900 <- potential_tracts_demo$B7O009
potential_tracts_demo$property_value_35000_plus <- potential_tracts_demo$B7O010


# units in structure (housing units)

potential_tracts_demo$units_1 <- potential_tracts_demo$B92001
potential_tracts_demo$units_2 <- potential_tracts_demo$B92002
potential_tracts_demo$units_3_4 <- potential_tracts_demo$B92003
potential_tracts_demo$units_5_9 <- potential_tracts_demo$B92004
potential_tracts_demo$units_10_P <- potential_tracts_demo$B92005


# year structure built (all housing units)

potential_tracts_demo$built_1950_1960 <- potential_tracts_demo$B96001
potential_tracts_demo$built_1940_1949 <- potential_tracts_demo$B96002
potential_tracts_demo$built_pre_1940 <- potential_tracts_demo$B96003



# year head moved into household (occupied housing units)

potential_tracts_demo$moved_1958_1960 <- potential_tracts_demo$CAJ001
potential_tracts_demo$moved_in_1954_1957 <- potential_tracts_demo$CAJ002
potential_tracts_demo$moved_in_1940_1953 <- potential_tracts_demo$CAJ003
potential_tracts_demo$moved_in_pre_1940 <- potential_tracts_demo$CAJ004

# persons in group quarters from printed report (persons in hhs)

potential_tracts_demo$persons_group_quarters<- potential_tracts_demo$B54001


# housing by condition

potential_tracts_demo$condition_sound <- potential_tracts_demo$B67001
potential_tracts_demo$condition_deteriorated <- potential_tracts_demo$B67002
potential_tracts_demo$condition_dilapidated <- potential_tracts_demo$B67003

# employment status
potential_tracts_demo$employed_males <- potential_tracts_demo$B82001
potential_tracts_demo$unemployed_males <- potential_tracts_demo$B82002
potential_tracts_demo$armed_forces_males <- potential_tracts_demo$B82003
potential_tracts_demo$not_in_lf_males <- potential_tracts_demo$B82004
potential_tracts_demo$employed_females <- potential_tracts_demo$B82005
potential_tracts_demo$unemployed_females <- potential_tracts_demo$B82006
potential_tracts_demo$armed_forces_females <- potential_tracts_demo$B82007
potential_tracts_demo$not_in_lf_females<- potential_tracts_demo$B82008


# plumbing: DID NOT CODE ALL OPTIONS
potential_tracts_demo$plumbing_sound_w_all_facilities <- potential_tracts_demo$B9V001

potential_tracts_demo$plumbing_deteriorating_w_all_facilities <- potential_tracts_demo$B9V004
potential_tracts_demo$plumbing_deteriorating_lackorshare_hwater <- potential_tracts_demo$B9V005
potential_tracts_demo$plumbing_deteriorating_lackorshare_privatetoilet <- potential_tracts_demo$B9V006
potential_tracts_demo$plumbing_delapidated <- potential_tracts_demo$B9V007

# bathrooms
potential_tracts_demo$one_bathroom <- potential_tracts_demo$B9Y001
potential_tracts_demo$more_than_one_bathroom <- potential_tracts_demo$B9Y002
potential_tracts_demo$shared_or_no_inside_bathroom <- potential_tracts_demo$B9Y003


# rent buckets
potential_tracts_demo$contract_rent_lt_20 <- potential_tracts_demo$CAV001
potential_tracts_demo$contract_rent_20_29 <- potential_tracts_demo$CAV002
potential_tracts_demo$contract_rent_30_39 <- potential_tracts_demo$CAV003
potential_tracts_demo$contract_rent_40_49 <- potential_tracts_demo$CAV004
potential_tracts_demo$contract_rent_50_59 <- potential_tracts_demo$CAV005
potential_tracts_demo$contract_rent_60_69 <- potential_tracts_demo$CAV006
potential_tracts_demo$contract_rent_70_79 <- potential_tracts_demo$CAV007
potential_tracts_demo$contract_rent_80_89 <- potential_tracts_demo$CAV008
potential_tracts_demo$contract_rent_90_99 <- potential_tracts_demo$CAV009
potential_tracts_demo$contract_rent_l00_119 <- potential_tracts_demo$CAV010
potential_tracts_demo$contract_rent_120_149 <- potential_tracts_demo$CAV011
potential_tracts_demo$contract_rent_150p <- potential_tracts_demo$CAV012
potential_tracts_demo$contract_rent_no_cash_rent <- potential_tracts_demo$CAV013


```


```{r creating additional variables relevant for analysis, include = FALSE}

# calculate population density (originally in meters squared area so scale to km)
potential_tracts_demo$pop_density <- potential_tracts_demo$tot_persons_printed/potential_tracts_demo$tract_area * 1000000

# pct non-white
potential_tracts_demo$pct_non_white_printed <- (potential_tracts_demo$black_printed +
                                      potential_tracts_demo$other_printed)/potential_tracts_demo$tot_persons_printed * 100

# pct black
potential_tracts_demo$pct_black_printed <- (potential_tracts_demo$black_printed)/potential_tracts_demo$tot_persons_printed * 100


# % foreign stock
potential_tracts_demo$pct_foreign_stock_printed<- (potential_tracts_demo$foreign_stock_printed)/potential_tracts_demo$tot_persons_printed * 100

# % foreign born
potential_tracts_demo$pct_foreign_born <- (potential_tracts_demo$foreign_born)/potential_tracts_demo$tot_persons_printed * 100

# pct hs grads

# calculate total persons who have school data
potential_tracts_demo$tot_school_persons <- potential_tracts_demo$no_school + potential_tracts_demo$school_yr_1_4  +
  potential_tracts_demo$school_yr_5_7 + potential_tracts_demo$school_yr_8 + potential_tracts_demo$school_yr_hs_1_3 +
  potential_tracts_demo$school_yr_hs_4 + potential_tracts_demo$school_yr_college_1_3 +
  potential_tracts_demo$school_yr_college_p

# calculate total persons whose highest edu attainment is hs completion or greater
potential_tracts_demo$tot_hs_grads <- potential_tracts_demo$school_yr_hs_4 +
  potential_tracts_demo$school_yr_college_1_3 +
  potential_tracts_demo$school_yr_college_p

# calculate hs grads
potential_tracts_demo$pct_hs_grad <- potential_tracts_demo$tot_hs_grads/potential_tracts_demo$tot_school_persons * 100

# calculate total persons whose highest edu attainment is some college completion or greater
potential_tracts_demo$tot_some_college <- potential_tracts_demo$school_yr_college_1_3 +
  potential_tracts_demo$school_yr_college_p

# calculate pct_some college
potential_tracts_demo$pct_some_college <- potential_tracts_demo$tot_some_college/potential_tracts_demo$tot_school_persons * 100


# calc weighted years of school
potential_tracts_demo$weighted_tot_years_school <- (potential_tracts_demo$no_school * 0 + potential_tracts_demo$school_yr_1_4 * 2  +
  potential_tracts_demo$school_yr_5_7 * 6 + potential_tracts_demo$school_yr_8 * 8 + potential_tracts_demo$school_yr_hs_1_3 * 10 +
  potential_tracts_demo$school_yr_hs_4 * 12 + potential_tracts_demo$school_yr_college_1_3 * 14 +
  potential_tracts_demo$school_yr_college_p * 16)/potential_tracts_demo$tot_school_persons



# need to calculate income next -> how to choose something for this?? https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-poverty-people.html

# based on the above source, the pverty level for families of 3 in 1959 was 2,324 -> create indicator of below or above 3k income, roughly the poverty line for a family of 3. 

# average household size according to the census in 1960 was 3.29 https://www.census.gov/library/publications/1962/dec/pc-s1-23.html#:~:text=The%20number%20of%20households%20in,of%20household%20was%203.29%20persons.

# sum families with income in 1959 <3k and then divide by total # families


potential_tracts_demo$all_families_with_income_data <- potential_tracts_demo$fam_income_less_1k + potential_tracts_demo$fam_income_1_2k + potential_tracts_demo$fam_income_2_3k +
potential_tracts_demo$fam_income_3_4k + potential_tracts_demo$fam_income_4_5k + potential_tracts_demo$fam_income_5_6k +
potential_tracts_demo$fam_income_6_7k + potential_tracts_demo$fam_income_7_8k + potential_tracts_demo$fam_income_8_9k +
potential_tracts_demo$fam_income_9_10k + potential_tracts_demo$fam_income_10_15k + potential_tracts_demo$fam_income_15_25k +
potential_tracts_demo$fam_income_25k_p

potential_tracts_demo$all_families_with_income_lt_3k <- potential_tracts_demo$fam_income_less_1k + potential_tracts_demo$fam_income_1_2k + potential_tracts_demo$fam_income_2_3k 

potential_tracts_demo$pct_families_below_3k_income <- (potential_tracts_demo$all_families_with_income_lt_3k/
                                                     potential_tracts_demo$all_families_with_income_data) * 100

potential_tracts_demo$all_families_with_income_lt_4k <- potential_tracts_demo$fam_income_less_1k + potential_tracts_demo$fam_income_1_2k + potential_tracts_demo$fam_income_2_3k +
  potential_tracts_demo$fam_income_3_4k 

potential_tracts_demo$pct_families_below_4k_income <-   (potential_tracts_demo$all_families_with_income_lt_4k/
                                                     potential_tracts_demo$all_families_with_income_data) * 100 


# add weighted family income
potential_tracts_demo$weighted_family_income = (potential_tracts_demo$fam_income_less_1k * 500 + 
                                                  potential_tracts_demo$fam_income_1_2k * 1500 + 
                                                  potential_tracts_demo$fam_income_2_3k * 2500 +
                                                  potential_tracts_demo$fam_income_3_4k * 3500 + 
                                                  potential_tracts_demo$fam_income_4_5k * 4500 + 
                                                  potential_tracts_demo$fam_income_5_6k * 5500 + 
                                                  potential_tracts_demo$fam_income_6_7k * 6500 + 
                                                  potential_tracts_demo$fam_income_7_8k * 7500 +
                                                  potential_tracts_demo$fam_income_8_9k * 8500 +
                                                  potential_tracts_demo$fam_income_9_10k * 9500 + 
                                                  potential_tracts_demo$fam_income_10_15k * 12500 + 
                                                  potential_tracts_demo$fam_income_15_25k * 20000 +
                                                  potential_tracts_demo$fam_income_25k_p * 25000)/potential_tracts_demo$all_families_with_income_data



# hhunits

# other type of vacancy status with other option
# N vacant for rent (vacant year-round housing units)
potential_tracts_demo$vacant_all <- potential_tracts_demo$vacant_for_rent_2 + potential_tracts_demo$vacant_for_sale_2 + 
  potential_tracts_demo$vacant_other_2

potential_tracts_demo$pct_vacant_all <- 100 * potential_tracts_demo$vacant_all/potential_tracts_demo$tot_hunits


# create var for occupied units which is all units minus vacant

potential_tracts_demo$occupied_units <- potential_tracts_demo$tot_hunits - potential_tracts_demo$vacant_all


# pct_owner_occupied out of all units
potential_tracts_demo$pct_owner_occupied <- 100 * potential_tracts_demo$owner_occupied/potential_tracts_demo$occupied_units


# pct renter occupied (occupied year round h units)
potential_tracts_demo$pct_renter_occupied <- 100 * potential_tracts_demo$renter_occupied/potential_tracts_demo$occupied_units


# pct units 1.01 or more people per room (highest category)
potential_tracts_demo$pct_one_point_0_one_people_per_room_or_more <- 100 *  potential_tracts_demo$persons_per_room_onepone_or_more/potential_tracts_demo$occupied_units


# average rent of owner occupied units
potential_tracts_demo$avg_monthly_contract_rent <- potential_tracts_demo$agg_monthly_contract_rent/ potential_tracts_demo$renter_occupied_units_reporting_rent

# potential_tracts_demo %>%  select(agg_monthly_contract_rent, renter_occupied_units_reporting_rent, avg_monthly_contract_rent, log_avg_monthly_contract_rent) %>% filter(avg_monthly_contract_rent > 300)

# potential_tracts_demo$avg_monthly_contract_rent[potential_tracts_demo$renter_occupied_units_reporting_rent == 0] <- NA
# potential_tracts_demo$avg_monthly_contract_rent[potential_tracts_demo$GISJOIN == 	"G08000100079" ] <- NA



# log average rent of owner occupied units
potential_tracts_demo$log_avg_monthly_contract_rent <- log(potential_tracts_demo$avg_monthly_contract_rent)



# https://archive.curbed.com/2018/4/10/17219786/buying-a-house-mortgage-government-gi-bill says median home value was 11,900 in 1960

potential_tracts_demo$houses_w_property_value_data <- potential_tracts_demo$property_value_u5k +
  potential_tracts_demo$property_value_5000_7400 + potential_tracts_demo$property_value_7500_9900 +
  potential_tracts_demo$property_value_10000_12400 + potential_tracts_demo$property_value_12500_14900 +
  potential_tracts_demo$property_value_15000_17400 + potential_tracts_demo$property_value_17500_19900 +
  potential_tracts_demo$property_value_20000_24900 + potential_tracts_demo$property_value_25000_34900 +
  potential_tracts_demo$property_value_35000_plus


# percent of houses of value under 5k

potential_tracts_demo$pct_houses_w_property_value_u5k <- 100* potential_tracts_demo$property_value_u5k/potential_tracts_demo$houses_w_property_value_data

# weighted property value

potential_tracts_demo$weighted_prop_value <- (potential_tracts_demo$property_value_u5k * 2500 +
                                                  potential_tracts_demo$property_value_5000_7400 * 6250  + 
                                                  potential_tracts_demo$property_value_7500_9900 * 8750 +
                                                  potential_tracts_demo$property_value_10000_12400 * 11250 + 
                                                  potential_tracts_demo$property_value_12500_14900 * ((15000-12500)/2 + 12500) +
                                                  potential_tracts_demo$property_value_15000_17400 * ((17500-15000)/2 + 15000) + 
                                                  potential_tracts_demo$property_value_17500_19900 * ((20000-17500)/2 + 17500) +
                                                  potential_tracts_demo$property_value_20000_24900 * ((25000-20000)/2 + 20000) + 
                                                  potential_tracts_demo$property_value_25000_34900 * ((35000-25000)/2 + 25000) +
                                                  potential_tracts_demo$property_value_35000_plus* (35000))/potential_tracts_demo$houses_w_property_value_data

# pct 1 unit houses
potential_tracts_demo$units_with_unit_data <- potential_tracts_demo$units_1 + potential_tracts_demo$units_2 + potential_tracts_demo$units_3_4 + potential_tracts_demo$units_5_9 + potential_tracts_demo$units_10_P
potential_tracts_demo$pct_single_unit <- potential_tracts_demo$units_1/potential_tracts_demo$units_with_unit_data * 100

# pct built pre 1940

potential_tracts_demo$pct_built_pre_1940 <- potential_tracts_demo$built_pre_1940/(potential_tracts_demo$built_1950_1960 + potential_tracts_demo$built_1940_1949 + potential_tracts_demo$built_pre_1940) * 100



# year head moved into household (occupied housing units)

potential_tracts_demo$pct_moved_pre_1940 <- potential_tracts_demo$moved_in_pre_1940/(potential_tracts_demo$moved_1958_1960 + potential_tracts_demo$moved_in_1954_1957 + potential_tracts_demo$moved_in_1940_1953 + potential_tracts_demo$moved_in_pre_1940) * 100

potential_tracts_demo$pct_moved_1958_1960 <- potential_tracts_demo$moved_1958_1960/(potential_tracts_demo$moved_1958_1960 + potential_tracts_demo$moved_in_1954_1957 + potential_tracts_demo$moved_in_1940_1953 + potential_tracts_demo$moved_in_pre_1940) * 100

# pct_pop group quarters

potential_tracts_demo$pct_persons_group_quarters <- 100 * potential_tracts_demo$persons_group_quarters/potential_tracts_demo$tot_persons_printed

# CONDITION

# housing by condition: pct deteriorated or dilapidated

potential_tracts_demo$pct_housing_deteriorated_dilap <- (potential_tracts_demo$condition_deteriorated + potential_tracts_demo$condition_dilapidated)/ (potential_tracts_demo$condition_sound + potential_tracts_demo$condition_deteriorated + potential_tracts_demo$condition_dilapidated) * 100

# pct males unemployed

potential_tracts_demo$pct_unemployed_males <- 100 * potential_tracts_demo$unemployed_males/
  (potential_tracts_demo$unemployed_males + potential_tracts_demo$employed_males
   + potential_tracts_demo$armed_forces_males + potential_tracts_demo$not_in_lf_males)  


# pct employed males over total

potential_tracts_demo$employed_males <- potential_tracts_demo$B82001
potential_tracts_demo$unemployed_males <- potential_tracts_demo$B82002
potential_tracts_demo$armed_forces_males <- potential_tracts_demo$B82003
potential_tracts_demo$not_in_lf_males <- potential_tracts_demo$B82004

potential_tracts_demo$pct_employed_out_of_all_males <- 100 * potential_tracts_demo$employed_males/
  (potential_tracts_demo$unemployed_males + potential_tracts_demo$employed_males +
     potential_tracts_demo$armed_forces_males + potential_tracts_demo$not_in_lf_males)



# plumbing: pct deteriorating or dilapidated
potential_tracts_demo$pct_plumbing_detdilap <- 100 * (potential_tracts_demo$plumbing_deteriorating_w_all_facilities  +
  potential_tracts_demo$plumbing_deteriorating_lackorshare_hwater +
  potential_tracts_demo$plumbing_deteriorating_lackorshare_privatetoilet +
  potential_tracts_demo$plumbing_delapidated )/potential_tracts_demo$tot_hunits

# bathrooms

potential_tracts_demo$pct_shared_or_bath_outside <- potential_tracts_demo$shared_or_no_inside_bathroom/ potential_tracts_demo$tot_hunits * 100
potential_tracts_demo$pct_more_than_one_bathroom <- potential_tracts_demo$more_than_one_bathroom/potential_tracts_demo$tot_hunits * 100


# rent buckets
potential_tracts_demo$contract_rent_lt_20 <- potential_tracts_demo$CAV001
potential_tracts_demo$contract_rent_20_29 <- potential_tracts_demo$CAV002
potential_tracts_demo$contract_rent_30_39 <- potential_tracts_demo$CAV003
potential_tracts_demo$contract_rent_40_49 <- potential_tracts_demo$CAV004
potential_tracts_demo$contract_rent_50_59 <- potential_tracts_demo$CAV005
potential_tracts_demo$contract_rent_60_69 <- potential_tracts_demo$CAV006
potential_tracts_demo$contract_rent_70_79 <- potential_tracts_demo$CAV007
potential_tracts_demo$contract_rent_80_89 <- potential_tracts_demo$CAV008
potential_tracts_demo$contract_rent_90_99 <- potential_tracts_demo$CAV009
potential_tracts_demo$contract_rent_l00_119 <- potential_tracts_demo$CAV010
potential_tracts_demo$contract_rent_120_149 <- potential_tracts_demo$CAV011
potential_tracts_demo$contract_rent_150p <- potential_tracts_demo$CAV012
potential_tracts_demo$contract_rent_no_cash_rent <- potential_tracts_demo$CAV013

all_houses_reporting_contract_rent <- sum(potential_tracts_demo$contract_rent_lt_20, na.rm = T) + sum(potential_tracts_demo$contract_rent_20_29, na.rm = T) +
  sum(potential_tracts_demo$contract_rent_30_39, na.rm = T) + sum(potential_tracts_demo$contract_rent_40_49 , na.rm = T) + 
  sum(potential_tracts_demo$contract_rent_50_59, na.rm = T) + sum(potential_tracts_demo$contract_rent_60_69, na.rm = T) +
  sum(potential_tracts_demo$contract_rent_70_79, na.rm = T) + sum(potential_tracts_demo$contract_rent_80_89 , na.rm = T) + 
  sum(potential_tracts_demo$contract_rent_90_99, na.rm = T) + sum(potential_tracts_demo$contract_rent_l00_119, na.rm = T) + 
  sum(potential_tracts_demo$contract_rent_120_149, na.rm = T) + sum(potential_tracts_demo$contract_rent_150p, na.rm = T) +
  sum(potential_tracts_demo$contract_rent_no_cash_rent, na.rm = T)
  

.25 * all_houses_reporting_contract_rent 

sum(potential_tracts_demo$contract_rent_lt_20, na.rm = T) + sum(potential_tracts_demo$contract_rent_20_29, na.rm = T) + sum(potential_tracts_demo$contract_rent_30_39, na.rm = T) + sum(potential_tracts_demo$contract_rent_40_49 , na.rm = T)

# pct with rent < $50 (approximately 25 percentile of rent)

potential_tracts_demo$pct_contract_rent_lt_50 <- 100 * (potential_tracts_demo$contract_rent_lt_20 + potential_tracts_demo$contract_rent_20_29 + potential_tracts_demo$contract_rent_30_39
                                              + potential_tracts_demo$contract_rent_40_49)/(potential_tracts_demo$contract_rent_lt_20 + potential_tracts_demo$contract_rent_20_29 +
                                                                                          potential_tracts_demo$contract_rent_30_39 + potential_tracts_demo$contract_rent_40_49 +
                                                                                          potential_tracts_demo$contract_rent_50_59 + potential_tracts_demo$contract_rent_60_69 +
                                                                                          potential_tracts_demo$contract_rent_70_79 + potential_tracts_demo$contract_rent_80_89 +
                                                                                          potential_tracts_demo$contract_rent_90_99 + potential_tracts_demo$contract_rent_l00_119 +
                                                                                          potential_tracts_demo$contract_rent_120_149 + potential_tracts_demo$contract_rent_150p)
# number of units reporting cash rent
potential_tracts_demo$reporting_contract_rent_calc <- potential_tracts_demo$contract_rent_lt_20 + potential_tracts_demo$contract_rent_20_29 +
                                                                                          potential_tracts_demo$contract_rent_30_39 + potential_tracts_demo$contract_rent_40_49 +
                                                                                          potential_tracts_demo$contract_rent_50_59 + potential_tracts_demo$contract_rent_60_69 +
                                                                                          potential_tracts_demo$contract_rent_70_79 + potential_tracts_demo$contract_rent_80_89 +
                                                                                          potential_tracts_demo$contract_rent_90_99 + potential_tracts_demo$contract_rent_l00_119 +
                                                                                          potential_tracts_demo$contract_rent_120_149 + potential_tracts_demo$contract_rent_150p

# weighted contract rent: 150+ coded as 150
potential_tracts_demo$weighted_cash_contract_rent <- (potential_tracts_demo$contract_rent_lt_20 * 10 + potential_tracts_demo$contract_rent_20_29  * 24.5 + 
  potential_tracts_demo$contract_rent_30_39 * 34.5 + potential_tracts_demo$contract_rent_40_49 * 44.5 + potential_tracts_demo$contract_rent_50_59 * 54.5 +
  potential_tracts_demo$contract_rent_60_69 * 64.5 + potential_tracts_demo$contract_rent_70_79 * 74.5 + potential_tracts_demo$contract_rent_80_89 * 84.5 +
  potential_tracts_demo$contract_rent_90_99 * 94.5 + potential_tracts_demo$contract_rent_l00_119 * 109.5 + potential_tracts_demo$contract_rent_120_149 * 134.5 +
  potential_tracts_demo$contract_rent_150p * 150)/potential_tracts_demo$reporting_contract_rent_calc

potential_tracts_demo$weighted_cash_contract_rent_lt_50 <- ifelse(potential_tracts_demo$weighted_cash_contract_rent < 50, 1, 0)





potential_tracts_demo$owner_occ_property_value_u5k <- potential_tracts_demo$CAO001
potential_tracts_demo$owner_occ_property_value_5000_7499 <- potential_tracts_demo$CAO002
potential_tracts_demo$owner_occ_property_value_7500_9999 <- potential_tracts_demo$CAO003
potential_tracts_demo$owner_occ_property_value_10000_12499 <- potential_tracts_demo$CAO004
potential_tracts_demo$owner_occ_property_value_12500_14999 <- potential_tracts_demo$CAO005
potential_tracts_demo$owner_occ_property_value_15000_17499 <- potential_tracts_demo$CAO006
potential_tracts_demo$owner_occ_property_value_17500_19999 <- potential_tracts_demo$CAO007
potential_tracts_demo$owner_occ_property_value_20000_24999 <- potential_tracts_demo$CAO008
potential_tracts_demo$owner_occ_property_value_25000_34999 <- potential_tracts_demo$CAO009
potential_tracts_demo$owner_occ_property_value_35000_plus <- potential_tracts_demo$CAO010




potential_tracts_demo$tot_owner_occ_with_value = potential_tracts_demo$owner_occ_property_value_u5k + potential_tracts_demo$owner_occ_property_value_5000_7499 + potential_tracts_demo$owner_occ_property_value_7500_9999 + potential_tracts_demo$owner_occ_property_value_10000_12499 + potential_tracts_demo$owner_occ_property_value_12500_14999  + potential_tracts_demo$owner_occ_property_value_15000_17499 + potential_tracts_demo$owner_occ_property_value_17500_19999 + potential_tracts_demo$owner_occ_property_value_20000_24999 + potential_tracts_demo$owner_occ_property_value_25000_34999 + potential_tracts_demo$owner_occ_property_value_35000_plus 






potential_tracts_demo$owner_occ_property_value = (potential_tracts_demo$owner_occ_property_value_u5k * 2500 + 
                                                potential_tracts_demo$owner_occ_property_value_5000_7499 * 6250 +
                                                potential_tracts_demo$owner_occ_property_value_7500_9999 * 8750 +
                                                potential_tracts_demo$owner_occ_property_value_10000_12499 * 11250 +
                                                potential_tracts_demo$owner_occ_property_value_12500_14999 * ((15000-12500)/2 + 12500)  +
                                                potential_tracts_demo$owner_occ_property_value_15000_17499 * ((17500-15000)/2 + 15000) +
                                                potential_tracts_demo$owner_occ_property_value_17500_19999 * ((20000-17500)/2 + 17500) +
                                                potential_tracts_demo$owner_occ_property_value_20000_24999 * ((25000-20000)/2 + 20000) +
                                                potential_tracts_demo$owner_occ_property_value_25000_34999 * ((35000-25000)/2 + 25000) +
                                                potential_tracts_demo$owner_occ_property_value_35000_plus * 35000)/potential_tracts_demo$tot_owner_occ_with_value




```


```{r get rid of extra columns}
# colnames(potential_tracts_demo)

potential_tracts_demo <- potential_tracts_demo %>%
  select(state:AREANAME, tot_persons_printed:owner_occ_property_value)

```




```{r dropping tracts with low density}

tracts_selected <- potential_tracts_demo %>%
  filter(pop_density >= 952.4427)



colnames(tracts_selected)



```

```{r join state region correspondence, include = FALSE}

tracts_selected <- left_join(tracts_selected, state_ab_region)

```


```{r join in land rent and value residuals, include = FALSE}

land_residuals_selected <- land_residuals %>%
  select(gisjoin_1960, resid_land_rent, resid_land_value)

tracts_selected <- left_join(tracts_selected, land_residuals_selected, by = c("GISJOIN" = "gisjoin_1960"))

```


```{r better cleaning final data, include = FALSE}

tracts_selected <- tracts_selected %>% 
  select(
    nhgisst_1960 = NHGISST,
    nhgiscty_1960 = NHGISCTY,
    nhgis_place_1940 = NHGISPLACE,
    holc_state = state,
    state_ab,
    region,
    holc_city = cityname,
    gisjoin_1960 = GISJOIN,
    numeric_city_code,
    pop_density_1960 = pop_density,
    citypop_1930 = citypop_total_1930,
    citypop_1940,
    citypop_1990,
    pct_change_citypop_30_90 = pct_change_pop_30_90,
    city_holc_area_radius = holc_area_radius,
    city_urb_area_90_radius = urb_area_90_radius,
    city_reg_estimated_multiplier = "reg estimated multiplier",
    city_reg_estimated_radius = "reg estimated radius",
    city_hh_1940,
    city_1940_pct_owner_occ_non_v:city_1940_pct_black,
    city_1940_pct_emp_males_14_plus,
    city_1940_pct_completed_hs,
    city_1940_pct_completed_hs_male_18_64,
    city_1940_pct_all_males_18_64_employed,
    city_1940_pct_all_males_14_plus_employed,
    city_1940_pct_completed_hs_25_plus,
    tract_area_1960 = tract_area,
    treatment,
    tot_persons_printed_1960 = tot_persons_printed,
    pct_non_white_1960 = pct_non_white_printed,
    pct_black_1960 = pct_black_printed,
    pct_foreign_born_1960 = pct_foreign_born,
    pct_hs_grad_1960 = pct_hs_grad,
    pct_some_college_1960 = pct_some_college,
    weighted_tot_years_school_1960 = weighted_tot_years_school,
    pct_vacant_1960 = pct_vacant_all,
    pct_owner_occupied_1960 = pct_owner_occupied,
    pct_renter_occupied_1960 = pct_renter_occupied,
    pct_one_point_0_one_people_per_room_or_more_1960 = pct_one_point_0_one_people_per_room_or_more,
    # avg contract rent got messed up, better to use weighted
    avg_monthly_contract_rent_1960 = avg_monthly_contract_rent,
    weighted_prop_value_1960 = weighted_prop_value,
    pct_single_unit_1960 = pct_single_unit,
    pct_housing_deteriorated_dilap_1960 = pct_housing_deteriorated_dilap,
    pct_unemployed_males_1960 = pct_unemployed_males,
    pct_employed_out_of_all_males_1960 = pct_employed_out_of_all_males,
    pct_more_than_one_bathroom_1960 = pct_more_than_one_bathroom,
    pct_contract_rent_lt_50_1960 = pct_contract_rent_lt_50,
    weighted_cash_contract_rent_1960 = weighted_cash_contract_rent,
    pct_families_below_3k_income_1960 = pct_families_below_3k_income,
    weighted_family_income_1960 = weighted_family_income,
    owner_occ_property_value_1960 = owner_occ_property_value,
    resid_land_rent_1960 = resid_land_rent,
    resid_land_value_1960 = resid_land_value
      ) %>%
  mutate(log_property_value_1960 = log(weighted_prop_value_1960),
         log_contract_rent_1960 = log(weighted_cash_contract_rent_1960),
         log_family_income_1960 = log(weighted_family_income_1960),
         log_property_value_1960 = log(owner_occ_property_value_1960),
         log_city_1940_avg_contract_rent = log(city_1940_avg_contract_rent),
         log_city_1940_avg_h_value_ = log(city_1940_avg_h_value_),
         log_city_1940_avg_wage_emp_males = log(city_1940_avg_wage_emp_males_14_p))

```



```{r}
colnames(tracts_selected)
```



```{r save as csv}

write.csv(tracts_selected, "tracts_selected.csv")

tracts_selected %>%
  filter(treatment == 1)
```



```{r merge with data_analysis_recode.csv for special use with associations, include = FALSE}

tracts_selected_sub <- tracts_selected %>%
  select(gisjoin_1960, region, citypop_1940, city_1940_pct_owner_occ_non_v:city_1940_pct_completed_hs_25_plus, log_property_value_1960:log_city_1940_avg_wage_emp_males)

data_for_analysis_recode_assoc <- left_join(data_for_analysis_recode, tracts_selected_sub)

write.csv(data_for_analysis_recode_assoc, "data_for_analysis_recode_assoc.csv")
```

```{r create dataset with selected tracts for control but real tracts for treatment, include = FALSE}

tracts_selected_control <- tracts_selected %>%
  filter(treatment == 1)

data_for_analysis_recode_sub <- data_for_analysis_recode %>%
  filter(citypop_1930 <= 60000, area_accounted_for_1960 >= .5) %>%
  mutate(nhgiscty_1960 = as.numeric(nhgiscty_1960))


data_for_analysis_recode_selected_control_d <- full_join(tracts_selected, data_for_analysis_recode_sub)

colnames(data_for_analysis_recode_selected_control_d)

data_for_analysis_recode_selected_control_d %>%
  filter(citypop_1930 <= 60000, treatment == 0) %>%
  group_by(holc_city, treatment) %>%
  summarise(sum_1 = mean(city_1940_avg_wage_emp_males_14_p),
            mean_pct_d = mean(pct_grade_d, na.rm = T))


write.csv(data_for_analysis_recode_selected_control_d, "data_for_analysis_recode_selected_control_d.csv")


data_for_analysis %>%
  filter(citypop_total <= 60000, area_accounted_for >= .5)

anti_join(tracts_selected, data_for_analysis, by = c("gisjoin_1960" = "GISJOIN"))
anti_join(data_for_analysis, tracts_selected, by = c("GISJOIN" = "gisjoin_1960"))
```



# SELECTED TRACTS SUMMARY STATISTICS


```{r}
all_city_summary <- tracts_selected %>% 
  select(holc_state, holc_city, treatment, citypop_1930:citypop_1990, pct_change_citypop_30_90, city_1940_pct_owner_occ_non_v:city_1940_pct_black) %>%
  unique() %>%
  view()

write_csv(all_city_summary, "all_city_summary.csv")
  
```

```{r}

all_city_summary %>%
  ggplot(aes(x = city_1940_pct_black, color = treatment)) +
  geom_density() +
  ggtitle("% Black Population (City Level), 1940")

all_city_summary %>%
  ggplot(aes(x = city_1940_avg_wage_emp_males_14_p, color = treatment)) +
  geom_density() +
  ggtitle("Average Wage Income for Employed Males 14+ (City Level), 1940")

all_city_summary %>%
  ggplot(aes(x = city_1940_pct_unemp_males_14_plus, color = treatment)) +
  geom_density() +
  ggtitle("% Unemployed Males 14+ (City Level), 1940")

all_city_summary %>%
  ggplot(aes(x = city_1940_pct_owner_occ_non_v, color = treatment)) +
  geom_density() +
  ggtitle("Density of % Owner Occupied Units (City Level), 1940")

all_city_summary %>%
  ggplot(aes(x = city_1940_avg_contract_rent, color = treatment)) +
  geom_density() +
  ggtitle("Average Monthly Contract Rent (City Level), 1940")

all_city_summary %>%
  ggplot(aes(x = city_1940_avg_h_value_, color = treatment)) +
  geom_density() +
  ggtitle("Average House Value (City Level), 1940")
```



```{r looking at summary statistics}

tracts_selected %>%
  mutate(count = 1) %>%
  filter(treatment == 0)

tracts_selected %>%
  mutate(count = 0) %>%
  group_by(cityname, state, treatment, citypop_total_1930, citypop_1990, pct_change_pop_30_90) %>%
  summarise(n_tracts = sum(count))%>%
  view()

unique(tracts_selected$treatment)

tracts_selected %>%
  filter(treatment == 0) %>%
  mutate(count = 1) %>%
  group_by(cityname) %>%
  summarise(n_tracts = sum(count)) %>%
  summarise(mean = mean(n_tracts))

tracts_selected %>%
  select(pop_density)

tracts_selected %>%
  mutate(count = 1) %>%
  group_by(state) %>%
  summarize(sum = sum(count))

tracts_selected %>%
  mutate(count = 1) %>%
  group_by(holc_city, treatment) %>%
  summarise(sum_count = sum(count)) %>%
  view()

```

```{r}
colnames(tracts_selected)
```


```{r summary statistics across tracts}
# average population

tracts_selected %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(tot_persons_printed))

tracts_selected %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(tot_persons_printed))

# pct_AA

tracts_selected %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_black_printed))

tracts_selected %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_black_printed))

# pct_foreign_born

tracts_selected %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_foreign_born))

tracts_selected %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_foreign_born))


# pct_unemployed_males

tracts_selected %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_unemployed_males))

tracts_selected %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_unemployed_males))

# pct_owner_occupied

tracts_selected %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_owner_occupied, na.rm = T))

tracts_selected %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_owner_occupied, na.rm = T))

# pct_contract_rent_lt_50

tracts_selected %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_contract_rent_lt_50, na.rm = T))

tracts_selected %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_contract_rent_lt_50, na.rm = T))

# pct_vacant_all"

tracts_selected %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_vacant_all, na.rm = T))

tracts_selected %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_vacant_all, na.rm = T))


# pct_one_point_0_one_people_per_room_or_more

tracts_selected %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_one_point_0_one_people_per_room_or_more, na.rm = T))

tracts_selected %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_one_point_0_one_people_per_room_or_more, na.rm = T))

#  "pct_single_unit"   

tracts_selected %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_single_unit, na.rm = T))

tracts_selected %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_single_unit, na.rm = T))

# pct_housing_deteriorated_dilap

tracts_selected %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(pct_housing_deteriorated_dilap, na.rm = T))

tracts_selected %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(pct_housing_deteriorated_dilap, na.rm = T))

# "weighted_cash_contract_rent"         

tracts_selected %>%
  filter(treatment == 1) %>%
  summarise(mean_persons = mean(weighted_cash_contract_rent, na.rm = T))

tracts_selected %>%
  filter(treatment == 0) %>%
  summarise(mean_persons = mean(weighted_cash_contract_rent, na.rm = T))



```



```{r prop_grade_d}

tracts_selected %>%
  ggplot(aes(x = pop_density, fill = treatment)) +
  geom_histogram(bins = 100) +
  facet_wrap(~treatment)

```

```{r}
tracts_selected %>%
  ggplot(aes(x = pop_density, color = treatment)) +
  geom_density() +
  ggtitle("Distribution of Population Density by Tract")

```

```{r}
tracts_selected %>%
  group_by(cityname, treatment) %>%
  summarise(citypop_1930_ = mean(citypop_total_1930)) %>%
  ggplot(aes(x = citypop_1930_, color = treatment)) +
  geom_density()
```

```{r}
tracts_selected %>%
  group_by(cityname, treatment) %>%
  summarise(citypop_1930_ = mean(citypop_total_1930)) %>%
  ggplot(aes(x = citypop_1930_, fill = treatment)) +
  geom_histogram(bins = 15) +
  ggtitle("Distribution of City Populations")
```

```{r}
tracts_selected %>%
  filter(treatment == 1) %>%
  group_by(cityname, state, treatment) %>%
  summarise(citypop_1930_ = mean(citypop_total_1930)) %>%
  view()
```

```{r}
tracts_selected %>%
  ggplot(aes(x = pct_black_printed, color = treatment)) +
  geom_histogram() +
  facet_grid(.~treatment)

tracts_selected %>%
  ggplot(aes(x = pct_black_printed, color = treatment)) +
  geom_density() +
  facet_grid(.~treatment)

tracts_selected %>%
  ggplot(aes(x = pct_black_printed, color = treatment)) +
  geom_density()
```

```{r}
tracts_selected %>%
  ggplot(aes(x = pct_owner_occupied, color = treatment)) +
  geom_density()
```

```{r}
tracts_selected %>%
  ggplot(aes(x = pct_unemployed_males, color = treatment)) +
  geom_density()
```

```{r}
tracts_selected %>%
  ggplot(aes(x = pct_contract_rent_lt_50, color = treatment)) +
  geom_density()
```

```{r}
tracts_selected %>%
  ggplot(aes(x = pct_vacant_all, color = treatment)) +
  geom_density()  
```


```{r}

tracts_selected %>%
  ggplot(aes(x = pct_single_unit, color = treatment)) +
  geom_density()

data_for_analysis %>%
  filter(citypop_total > 60000) %>%
  group_by(city) %>%
  summarise(mean(citypop_total))

```


```{r}
tracts_selected %>%
  filter(cityname == "San Jose")
```


```{r}

control_cities <- tracts_selected %>%
  filter(treatment == 0) %>%
  group_by(cityname, state, treatment) %>%
  summarize(growth_rate = mean(pct_change_pop_30_90))

treatment_cities <- tracts_selected %>%
  filter(treatment == 1) %>%
  group_by(cityname, state, treatment) %>%
  summarize(growth_rate = mean(pct_change_pop_30_90))

mean(control_cities$growth_rate)

mean(treatment_cities$growth_rate)

tracts_selected %>%
  #filter(treatment == 0) %>%
  group_by(cityname, state, treatment) %>%
  summarize(growth_rate = mean(pct_change_pop_30_90)) %>%
  ggplot(aes(x = growth_rate, fill = treatment)) +
  geom_histogram() +
  facet_grid(~treatment) +
  ggtitle("% Change in Population of Treatment and Control Cities, 1930-1990")


tracts_selected %>%
  filter(cityname == "Gadsden") %>%
  select(pop_density)

```

```{r}
tracts_selected %>%
  mutate(count = 1) %>%
  group_by(holc_city, holc_state, treatment, numeric_city_code) %>%
  summarize(tot_tracts = sum(count)) %>%
  view()

summary(tracts_selected$tract_area)
```


```{r}
city_only <- tracts_selected %>%
  select(holc_city, treatment, numeric_city_code, city_1940_pct_owner_occ_non_v:city_1940_pct_completed_hs_25_plus) %>%
  unique()

city_only %>%
  ggplot() +
  geom_density(aes(x = city_1940_pct_completed_hs), color = "red") +
  geom_density(aes(x = city_1940_pct_completed_hs_male_18_64), color = "blue") +
  geom_density(aes(x = city_1940_pct_completed_hs_25_plus), color = "green")
```



```{r}
city_only %>%
  ggplot() +
  geom_density(aes(x = city_1940_pct_all_males_14_plus_employed), color = "red") +
  geom_density(aes(x = city_1940_pct_all_males_18_64_employed), color = "blue") +
  geom_density(aes(x = city_1940_pct_emp_males_14_plus), color = "green") +
  facet_wrap(~treatment)
  
```


```{r}
ipums_1940_person_level %>%
  ggplot(aes(x = pct_completed_hs)) +
  geom_histogram()
```


```{r}
ipums_1940_person_level %>%
  ggplot(aes(x = pct_completed_hs_male_18_64)) +
  geom_histogram()

```

```{r}
tracts_selected %>%
  mutate(count = 1) %>%
  group_by(holc_city, holc_state, treatment) %>%
  summarise(sum_count = sum(count), mean_hs = mean(city_1940_pct_completed_hs_25_plus)) %>%
  group_by(treatment) %>%
  summarise(mean_hs_treatment = mean(mean_hs))
```

