---
title: "Untitled"
author: "Maria Burzillo"
date: "2/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r load data, include = FALSE}

test_intersect_2010_1960 <- read.csv("Overlay Files from QGIS/test_intersect_2010_1960.csv") %>%
  # intersect over 2010 tract area 
  mutate(intersect_over_2010_tract = intersect_2010_1960_area/Shape_area_2,
         intersect_over_1960_tract = intersect_2010_1960_area/SHAPE_AREA)

colnames(test_intersect_2010_1960)

```

## Including Plots

You can also embed plots, for example:

```{r summarize}
test_intersect_2010_1960 %>%
  mutate(count = 1) %>%
  group_by(GISJOIN) %>%
  summarise(sum_count = sum(count)) %>%
  summarise(mean_intersect_areas_in_1960_tract = mean(sum_count),
            median_intersect_areas_in_1960_tract = median(sum_count))
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}

# lots of the intersect areas represent negligible areas
test_intersect_2010_1960 %>%
  ggplot(aes(x = intersect_over_tract)) +
  geom_histogram()
```


```{r}
# Q: how many tracts only have 1 intersect area? 595 out of the 961 tracts are 90% covered by 1 area
# more intersect areas entirely cover 2010 tracts, which makes sense because 2010 tracts should be smaller on average

test_intersect_2010_1960 %>%
  filter(intersect_over_1960_tract > .90 ) 

```


```{r coding 2010 variables}

test_intersect_2010_1960_edit <- test_intersect_2010_1960 %>%
  mutate(black_or_combo_2010 = nhgis0028_ds176_20105_2010_tract_JMEE001,
         tot_pop_2010 = nhgis0028_ds176_20105_2010_tract_JMAE001,
         tot_in_poverty_level_q_2010 = nhgis0028_ds176_20105_2010_tract_JOFE001,
         tot_below_poverty_level_2010 = nhgis0028_ds176_20105_2010_tract_JOFE002,
         pct_black_or_combo_2010 = black_or_combo_2010 / tot_pop_2010 * 100,
         pop_2010_in_intersect = intersect_over_2010_tract * tot_pop_2010) %>%
  select(-nhgis0028_ds176_20105_2010_tract_JMEE001, -nhgis0028_ds176_20105_2010_tract_JMAE001)

colnames(test_intersect_2010_1960_edit)

```

```{r}
test_1960_interpolation <- test_intersect_2010_1960_edit  %>%
  group_by(tracts_selected_cityname, GISJOIN, tracts_selected_tot_persons_printed) %>%
  mutate(tot_2010_pop_in_1960_tract = sum(pop_2010_in_intersect), interpolation_weight = pop_2010_in_intersect/tot_2010_pop_in_1960_tract, 
         sum_intersect_over_1960_tract = sum(intersect_over_1960_tract)) %>%
  select(tracts_selected_cityname, GISJOIN, intersect_over_1960_tract, sum_intersect_over_1960_tract, tracts_selected_tot_persons_printed, tot_pop_2010, intersect_over_2010_tract,
         pop_2010_in_intersect, tot_2010_pop_in_1960_tract, interpolation_weight, black_or_combo_2010, tracts_selected_pct_black_printed, tracts_selected_black_printed,
         tot_pop_2010, tot_in_poverty_level_q_2010, tot_below_poverty_level_2010)
```

```{r}
test_1960_interpolation %>%
  filter(tracts_selected_cityname == "Baton Rouge", GISJOIN == "G22003300001")
```

```{r}
test_1960_2010_by_tract %>%
  filter( GISJOIN == "G22003300001")
```


```{r}
test_1960_interpolation %>%
  ggplot(aes(x = intersect_over_1960_tract,  pop_2010_in_intersect)) +
  geom_point()

```


```{r}

# evidence that this worked
test_1960_interpolation %>%
  mutate(pct_2010_pop_in_intersect = pop_2010_in_intersect/tot_pop_2010) %>%
  ggplot(aes(x = intersect_over_2010_tract,  pct_2010_pop_in_intersect)) +
  geom_point()

```


```{r}

test_1960_interpolation %>%
  ggplot(aes(x = tot_2010_pop_in_1960_tract)) +
  geom_histogram()


```



```{r}
test_1960_interpolation %>%
  ggplot(aes(x = interpolation_weight)) +
  geom_histogram()

```


```{r converting to tract level data and sanity checks, include = FALSE}

# data convention: est in front means that is has been interpolated/estimated from 2010 to 1990

test_1960_2010_by_tract <- test_1960_interpolation %>%
  # generate the estimated number of black or black combo individuals in the intersect area
  mutate(est_black_or_combo_2010_intersect = black_or_combo_2010 * interpolation_weight,
         est_pop_2010_interpolated = tot_pop_2010 * interpolation_weight,
         est_n_poverty_level_2010 = tot_in_poverty_level_q_2010 * interpolation_weight,
         est_tot_below_poverty_level_2010 = tot_below_poverty_level_2010 * interpolation_weight) %>%
  group_by(tracts_selected_cityname, GISJOIN, tot_2010_pop_in_1960_tract, tracts_selected_tot_persons_printed, 
           tracts_selected_pct_black_printed, tracts_selected_black_printed) %>%
  # sum all the estimated intersect numbers within a tract
  summarize(black_or_combo_2010_in_1960_tract = sum(est_black_or_combo_2010_intersect),
            pop_2010_in_1960_tract = sum(est_pop_2010_interpolated),
            pct_black_or_combo_2010_in_2016_tract = black_or_combo_2010_in_1960_tract/pop_2010_in_1960_tract * 100,
            n_poverty_level_2010_in_2016_tract = sum(est_n_poverty_level_2010),
            tot_below_poverty_level_2010_in_2016_tract = sum(est_tot_below_poverty_level_2010), 
            pct_below_poverty_level_2010_in_2016_tract = tot_below_poverty_level_2010_in_2016_tract/n_poverty_level_2010_in_2016_tract * 100) %>%
  unique()



```


```{r}

test_1960_2010_by_tract %>%
  ggplot(aes(x = pct_below_poverty_level_2010_in_2016_tract)) +
  geom_histogram()

sum(test_1960_2010_by_tract$est_pct_below_poverty_level_2010 > 100)

```

```{r}
write.csv(test_1960_2010_by_tract, "test_1960_2010_by_tract.csv")
```

